// apps/qwik-web/src/routes/[owner]/[name]/pull-requests/new/create/index.tsx
import { component$ } from "@builder.io/qwik";
import { Link, type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { PullRequestCreateForm } from "~/components/pull-requests/PullRequestFlow";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import {
  comparePullRequestBranches,
  getRepository,
  listPullRequests,
  type RepositoryCompare,
} from "~/lib/api";
import { decodePullRequestSource } from "~/lib/pull-request-flow";

export const useCreatePullRequestPage = routeLoader$(async ({ params, url }) => {
  const from = url.searchParams.get("from") ?? undefined;
  const targetBranch = url.searchParams.get("targetBranch") ?? undefined;
  const [repo, pullRequests] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
  ]);
  const selection = decodePullRequestSource(from);
  const compare =
    selection && targetBranch
      ? await comparePullRequestBranches(params.owner, params.name, {
          source_branch: selection.branch,
          source_repo_url: selection.url,
          source_repository_id: selection.repositoryId,
          target_branch: targetBranch,
        }).catch(() => null)
      : null;
  const defaultTitle =
    selection && targetBranch
      ? defaultPullRequestTitle(selection.branch, targetBranch, compare)
      : "";

  return {
    baseHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}`,
    defaultTitle,
    pullRequestsCount: pullRequests.pagination.total,
    repo,
    selection,
    targetBranch,
  };
});

export default component$(() => {
  const route = useCreatePullRequestPage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="pull-requests"
        pullRequestsCount={route.value.pullRequestsCount}
        repo={route.value.repo}
      />
      <RepoPageContent>
        <section class="pull-request-flow__page">
          <div>
            <h2 class="pull-request-flow__page-title">New pull request</h2>
            <p class="issue-detail-page__meta">
              Add the final details and create the pull request.
            </p>
          </div>

          {route.value.selection && route.value.targetBranch ? (
            <PullRequestCreateForm
              baseHref={route.value.baseHref}
              defaultTitle={route.value.defaultTitle}
              name={route.value.repo.name}
              owner={route.value.repo.owner_handle}
              selection={route.value.selection}
              targetBranch={route.value.targetBranch}
            />
          ) : (
            <div class="pull-request-flow__missing">
              <h3 class="pull-request-flow__missing-title">Choose branches first</h3>
              <p class="issue-detail-page__meta">
                A source and target branch are required before creating a pull request.
              </p>
              <Link
                class="settings-resource-panel__secondary-button"
                href={`${route.value.baseHref}/pull-requests/new`}
              >
                Start over
              </Link>
            </div>
          )}
        </section>
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Create Pull Request · Diggit",
};

function defaultPullRequestTitle(
  sourceBranch: string,
  targetBranch: string,
  compare: RepositoryCompare | null,
) {
  if (compare?.ahead_commits.length === 1) {
    return firstLine(compare.ahead_commits[0]?.message ?? "");
  }
  return `Merge from ${sourceBranch} to ${targetBranch}`;
}

function firstLine(value: string) {
  return value.split(/\r?\n/)[0]?.trim() || value.trim();
}

// apps/web/src/app/[owner]/[name]/pull-requests/new/create/page.tsx
import { PullRequestCreateForm } from "@/components/PullRequestFlow";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { comparePullRequestBranches, getRepository, listPullRequests, type RepositoryCompare } from "@/lib/api";
import { decodePullRequestSource } from "@/lib/pull-request-flow";
import Link from "next/link";

type Props = {
  params: Promise<{ owner: string; name: string }>;
  searchParams: Promise<{
    from?: string;
    targetBranch?: string;
  }>;
};

export default async function CreatePullRequestPage({ params, searchParams }: Props) {
  const { owner, name } = await params;
  const { from, targetBranch } = await searchParams;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const baseHref = repoHref(decodedOwner, decodedName);
  const [repo, pullRequests] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [], pagination: { page: 1, limit: 1, total: 0, totalPages: 0 } })),
  ]);
  const selection = decodePullRequestSource(from);
  const compare =
    selection && targetBranch
      ? await comparePullRequestBranches(decodedOwner, decodedName, {
          source_branch: selection.branch,
          source_repo_url: selection.url,
          source_repository_id: selection.repositoryId,
          target_branch: targetBranch,
        }).catch(() => null)
      : null;
  const defaultTitle = selection && targetBranch ? defaultPullRequestTitle(selection.branch, targetBranch, compare) : "";

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="pull-requests" pullRequestsCount={pullRequests.pagination?.total ?? pullRequests.data.length} repo={repo} />

      <RepoPageContent>
        <section className="grid gap-4">
          <div>
            <h2 className="text-2xl font-semibold tracking-tight">New pull request</h2>
            <p className="text-[#59636e]">Add the final details and create the pull request.</p>
          </div>

          {selection && targetBranch ? (
            <PullRequestCreateForm
              baseHref={baseHref}
              defaultTitle={defaultTitle}
              name={decodedName}
              owner={decodedOwner}
              selection={selection}
              targetBranch={targetBranch}
            />
          ) : (
            <div className="grid gap-3 rounded-2xl border border-[#d0d7de] bg-white p-6 text-center">
              <h3 className="text-lg font-semibold">Choose branches first</h3>
              <p className="text-[#59636e]">A source and target branch are required before creating a pull request.</p>
              <Link className="justify-self-center rounded-lg border border-[#d0d7de] bg-white px-4 py-2 font-semibold" href={`${baseHref}/pull-requests/new`}>
                Start over
              </Link>
            </div>
          )}
        </section>
      </RepoPageContent>
    </div>
  );
}

function defaultPullRequestTitle(sourceBranch: string, targetBranch: string, compare: RepositoryCompare | null) {
  if (compare?.ahead_commits.length === 1) {
    return firstLine(compare.ahead_commits[0]?.message ?? "");
  }
  return `Merge from ${sourceBranch} to ${targetBranch}`;
}

function firstLine(value: string) {
  return value.split(/\r?\n/)[0]?.trim() || value.trim();
}
