// apps/web/src/app/admin/page.tsx
import Link from "next/link";

export default function AdminPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">Server administration</p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">Admin</h1>
        <p className="text-[#59636e]">
          Manage federation policy and inspect server-to-server activity from one place.
        </p>
      </section>

      <section className="grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-4">
        <Link className="grid gap-3.5 rounded-md border border-[#d0d7de] bg-white p-4" href="/admin/servers">
          <strong>Federated servers</strong>
          <span className="text-[#59636e]">Whitelist, blacklist, and review known remote hosts.</span>
        </Link>
        <Link className="grid gap-3.5 rounded-md border border-[#d0d7de] bg-white p-4" href="/admin/activity">
          <strong>Activity log</strong>
          <span className="text-[#59636e]">Inspect inbound and outbound ActivityPub messages.</span>
        </Link>
        <Link className="grid gap-3.5 rounded-md border border-[#d0d7de] bg-white p-4" href="/admin/runners">
          <strong>Server runners</strong>
          <span className="text-[#59636e]">Manage server-scope Gitea-compatible runners.</span>
        </Link>
      </section>
    </div>
  );
}

// apps/qwik-web/src/routes/admin/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { Link } from "@builder.io/qwik-city";

export default component$(() => {
  return (
    <div class="admin-page">
      <section class="admin-page__hero">
        <p class="admin-page__eyebrow">Server administration</p>
        <h1 class="admin-page__title">Admin</h1>
        <p class="admin-page__description">
          Manage federation policy and inspect server-to-server activity from
          one place.
        </p>
      </section>

      <section class="admin-page__grid">
        <Link class="admin-page__card" href="/admin/servers">
          <strong>Federated servers</strong>
          <span class="admin-page__card-copy">
            Whitelist, blacklist, and review known remote hosts.
          </span>
        </Link>
        <Link class="admin-page__card" href="/admin/activity">
          <strong>Activity log</strong>
          <span class="admin-page__card-copy">
            Inspect inbound and outbound ActivityPub messages.
          </span>
        </Link>
        <Link class="admin-page__card" href="/admin/runners">
          <strong>Server runners</strong>
          <span class="admin-page__card-copy">
            Manage server-scope Gitea-compatible runners.
          </span>
        </Link>
      </section>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Admin · Diggit",
};
