// apps/web/src/components/ForkButton.tsx
"use client";

import { apiBaseUrl, publicApiBaseUrl } from "@/lib/runtime-config";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { getAuthSession } from "@/lib/auth-session";

const API_URL = apiBaseUrl();
const PUBLIC_API_URL = publicApiBaseUrl();

type ForkButtonProps = {
  owner: string;
  name: string;
  initialForks: number;
};

export function ForkButton({ owner, name, initialForks }: ForkButtonProps) {
  const router = useRouter();
  const [forks, setForks] = useState(initialForks);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [message, setMessage] = useState("");

  async function fork() {
    const session = getAuthSession();
    if (!session) {
      setMessage("Sign in to fork");
      return;
    }

    setIsSubmitting(true);

    try {
      if (session.kind === "federated") {
        const response = await fetch(`${session.homeServer}/auth/federated/fork`, {
          method: "POST",
          headers: {
            authorization: `Bearer ${session.homeToken}`,
            "content-type": "application/json",
          },
          body: JSON.stringify({
            source_repo_url: `${PUBLIC_API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`,
          }),
        });

        if (!response.ok) {
          setMessage(await responseErrorMessage(response));
          return;
        }

        const forkedRepo = (await response.json()) as { http_url: string; owner_handle: string; name: string };
        setForks((value) => value + 1);
        setMessage("Fork created on your home server.");
        window.location.href = forkedRepo.http_url.replace(/\.git$/, "");
        return;
      }

      const response = await fetch(`${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/fork`, {
        method: "POST",
        headers: {
          authorization: `Bearer ${session.token}`,
          "content-type": "application/json",
        },
        body: JSON.stringify({}),
      });

      if (!response.ok) {
        setMessage(await responseErrorMessage(response));
        return;
      }

      const forkedRepo = (await response.json()) as { owner_handle: string; name: string };
      setForks((value) => value + 1);
      setMessage("");
      router.push(`/${encodeURIComponent(forkedRepo.owner_handle)}/${encodeURIComponent(forkedRepo.name)}`);
    } catch {
      setMessage("Failed to fork repository");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <div className="flex items-center gap-2">
      <button
        className="cursor-pointer rounded-md border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 font-semibold hover:border-[#0969da] hover:text-[#0969da]"
        disabled={isSubmitting}
        type="button"
        onClick={fork}
      >
        Fork
      </button>
      <span className="text-[#59636e]">{forks}</span>
      {message ? <span className="text-xs text-[#59636e]">{message}</span> : null}
    </div>
  );
}

async function responseErrorMessage(response: Response) {
  try {
    const payload = (await response.json()) as { error?: string };
    if (payload.error) {
      return payload.error;
    }
  } catch {
    // Fall through to the status-based message.
  }
  return `Failed: ${response.status}`;
}

// apps/qwik-web/src/components/repository/ForkButton.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { useNavigate } from "@builder.io/qwik-city";
import { getAuthSession } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type ForkButtonProps = {
  owner: string;
  name: string;
  initialForks: number;
};

export const ForkButton = component$(
  ({ owner, name, initialForks }: ForkButtonProps) => {
    const nav = useNavigate();
    const forks = useSignal(initialForks);
    const isSubmitting = useSignal(false);
    const message = useSignal("");

    const fork = $(async () => {
      const session = getAuthSession();
      if (!session) {
        message.value = "Sign in to fork";
        return;
      }

      isSubmitting.value = true;

      try {
        if (session.kind === "federated") {
          const response = await fetch(`${session.homeServer}/auth/federated/fork`, {
            method: "POST",
            headers: {
              authorization: `Bearer ${session.homeToken}`,
              "content-type": "application/json",
            },
            body: JSON.stringify({
              source_repo_url: `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`,
            }),
          });

          if (!response.ok) {
            message.value = await responseErrorMessage(response);
            return;
          }

          const forkedRepo = (await response.json()) as {
            http_url: string;
          };
          forks.value += 1;
          message.value = "Fork created on your home server.";
          window.location.href = forkedRepo.http_url.replace(/\.git$/, "");
          return;
        }

        const response = await fetch(
          `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/fork`,
          {
            method: "POST",
            headers: {
              authorization: `Bearer ${session.token}`,
              "content-type": "application/json",
            },
            body: JSON.stringify({}),
          },
        );

        if (!response.ok) {
          message.value = await responseErrorMessage(response);
          return;
        }

        const forkedRepo = (await response.json()) as {
          owner_handle: string;
          name: string;
        };
        forks.value += 1;
        message.value = "";
        await nav(
          `/${encodeURIComponent(forkedRepo.owner_handle)}/${encodeURIComponent(forkedRepo.name)}`,
        );
      } catch {
        message.value = "Failed to fork repository";
      } finally {
        isSubmitting.value = false;
      }
    });

    return (
      <div class="repo-fork">
        <button
          class="repo-fork__button"
          disabled={isSubmitting.value}
          type="button"
          onClick$={fork}
        >
          Fork
        </button>
        <span class="repo-fork__count">{forks.value}</span>
        {message.value ? <span class="repo-fork__message">{message.value}</span> : null}
      </div>
    );
  },
);

async function responseErrorMessage(response: Response) {
  try {
    const payload = (await response.json()) as { error?: string };
    if (payload.error) {
      return payload.error;
    }
  } catch {
    // Fall through to the status-based message.
  }

  return `Failed: ${response.status}`;
}
