// apps/web/src/components/RepoHeader.tsx
import Link from "next/link";
import { ForkButton } from "@/components/ForkButton";
import { StarButton } from "@/components/StarButton";
import type { Repository } from "@/lib/api";

type RepoHeaderProps = {
  activeTab: "actions" | "code" | "issues" | "pull-requests" | "settings";
  issuesCount?: number;
  pullRequestsCount?: number;
  repo: Repository;
};

export function RepoHeader({ activeTab, issuesCount = 0, pullRequestsCount = 0, repo }: RepoHeaderProps) {
  const ownerProfile = repoOwnerProfile(repo);
  const baseHref = repoHref(repo.owner_handle, repo.name);

  return (
    <section className="-mx-6 border-b border-[#d0d7de] bg-white px-6 pt-2">
      <div className="flex flex-wrap items-start justify-between gap-4 pb-4">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2 text-xl">
            <Link className="font-semibold text-[#0969da] hover:underline" href={ownerProfile.href}>
              {ownerProfile.handle}
            </Link>
            <span className="text-[#59636e]">/</span>
            <Link className="min-w-0 break-all text-xl font-semibold text-[#0969da] hover:underline" href={baseHref}>
              {repo.name}
            </Link>
            <span className="rounded-full border border-[#d0d7de] px-2 py-0.5 text-xs font-semibold text-[#59636e]">
              {repo.visibility}
            </span>
          </div>
          <p className="mt-2 text-[#59636e]">
            {repo.remote_server ? `Mirrored from ${repo.remote_server}` : "Local repository"}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <ForkButton initialForks={repo.forks_count ?? 0} name={repo.name} owner={repo.owner_handle} />
          <StarButton
            initialStarred={repo.viewer_has_starred}
            initialStars={repo.stars_count}
            name={repo.name}
            owner={repo.owner_handle}
          />
        </div>
      </div>

      <nav aria-label="Repository" className="flex gap-1 overflow-x-auto">
        <RepoTab active={activeTab === "code"} href={baseHref} label="Code" />
        {repo.issues_enabled ? <RepoTab active={activeTab === "issues"} href={`${baseHref}/issues`} label="Issues" count={issuesCount} /> : null}
        {repo.pull_requests_enabled ? (
          <RepoTab
            active={activeTab === "pull-requests"}
            href={`${baseHref}/pull-requests`}
            label="Pull requests"
            count={pullRequestsCount}
          />
        ) : null}
        <RepoTab active={activeTab === "actions"} href={`${baseHref}/actions`} label="Actions" />
        <RepoTab active={activeTab === "settings"} href={`${baseHref}/settings`} label="Settings" />
      </nav>
    </section>
  );
}

export function repoHref(owner: string, name: string) {
  return `/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`;
}

function RepoTab({
  active = false,
  count,
  href,
  label,
}: {
  active?: boolean;
  count?: number;
  href: string;
  label: string;
}) {
  return (
    <Link
      className={`flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 font-semibold ${
        active
          ? "border-[#fd8c73] text-[#1f2328]"
          : "border-transparent text-[#59636e] hover:border-[#d0d7de] hover:text-[#1f2328]"
      }`}
      href={href}
    >
      <span>{label}</span>
      {typeof count === "number" ? (
        <span className="rounded-full bg-[#eaeef2] px-2 py-0.5 text-xs text-[#1f2328]">{count}</span>
      ) : null}
    </Link>
  );
}

function repoOwnerProfile(repo: Repository) {
  const handle = repo.owner?.handle ?? repo.owner_handle;
  const kind = repo.owner?.kind === "organization" ? "organizations" : "users";

  return {
    handle,
    href: `/${kind}/${encodeURIComponent(handle)}`,
  };
}

// apps/qwik-web/src/components/repository/RepoHeader.tsx
import { Slot, component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import { CurrentUserNavActions } from "~/components/navigation/NavActions";
import { ForkButton } from "~/components/repository/ForkButton";
import { StarButton } from "~/components/repositories/StarButton";
import { type Repository } from "~/lib/api";
import { userProfileHref } from "~/lib/user-profile";

type RepoHeaderProps = {
  activeTab:
    | "actions"
    | "code"
    | "issues"
    | "pull-requests"
    | "releases"
    | "settings";
  issuesCount?: number;
  pullRequestsCount?: number;
  releasesCount?: number;
  repo: Repository;
};

export const RepoHeader = component$(
  ({
    activeTab,
    issuesCount = 0,
    pullRequestsCount = 0,
    releasesCount = 0,
    repo,
  }: RepoHeaderProps) => {
    const ownerHandle = repo.owner?.handle ?? repo.owner_handle;
    const ownerHref =
      repo.owner?.kind === "organization"
        ? `/organizations/${encodeURIComponent(ownerHandle)}`
        : userProfileHref(ownerHandle);
    const baseHref = `/${encodeURIComponent(repo.owner_handle)}/${encodeURIComponent(
      repo.name,
    )}`;
    const repoHref = `${baseHref}/`;

    return (
      <section class="repo-header">
        <div class="repo-header__top">
          <div class="repo-header__title-wrap">
            <div class="repo-header__title">
              <Link class="repo-header__owner" href={ownerHref}>
                {ownerHandle}
              </Link>
              <span class="repo-header__separator">/</span>
              <Link class="repo-header__name" href={repoHref}>
                {repo.name}
              </Link>
              <span class="repo-header__visibility">{repo.visibility}</span>
            </div>
          </div>

          <div class="repo-header__actions">
            <div class="repo-header__repo-actions">
              <ForkButton
                initialForks={repo.forks_count ?? 0}
                name={repo.name}
                owner={repo.owner_handle}
              />
              <StarButton
                initialStarred={repo.viewer_has_starred}
                initialStars={repo.stars_count}
                name={repo.name}
                owner={repo.owner_handle}
              />
            </div>
            <CurrentUserNavActions class="repo-header__nav-actions" />
          </div>
        </div>

        <nav aria-label="Repository" class="repo-tabs">
          <Link
            class={[
              "repo-tabs__tab",
              activeTab === "code" ? "repo-tabs__tab--active" : "",
            ]}
            href={repoHref}
          >
            Code
          </Link>
          {repo.issues_enabled ? (
            <Link
              class={[
                "repo-tabs__tab",
                activeTab === "issues" ? "repo-tabs__tab--active" : "",
              ]}
              href={`${baseHref}/issues/`}
            >
              Issues
              <span class="repo-tabs__count">{issuesCount}</span>
            </Link>
          ) : null}
          {repo.pull_requests_enabled ? (
            <Link
              class={[
                "repo-tabs__tab",
                activeTab === "pull-requests" ? "repo-tabs__tab--active" : "",
              ]}
              href={`${baseHref}/pull-requests/`}
            >
              Pull requests
              <span class="repo-tabs__count">{pullRequestsCount}</span>
            </Link>
          ) : null}
          <Link
            class={[
              "repo-tabs__tab",
              activeTab === "releases" ? "repo-tabs__tab--active" : "",
            ]}
            href={`${baseHref}/releases/`}
          >
            Releases
            <span class="repo-tabs__count">{releasesCount}</span>
          </Link>
          <Link
            class={[
              "repo-tabs__tab",
              activeTab === "actions" ? "repo-tabs__tab--active" : "",
            ]}
            href={`${baseHref}/actions/`}
          >
            Actions
          </Link>
          <Link
            class={[
              "repo-tabs__tab",
              activeTab === "settings" ? "repo-tabs__tab--active" : "",
            ]}
            href={`${baseHref}/settings/`}
          >
            Settings
          </Link>
        </nav>
      </section>
    );
  },
);

export const RepoPageContent = component$(() => {
  return (
    <div class="repo-page-shell">
      <Slot />
    </div>
  );
});
