// apps/web/src/components/SyncForkButton.tsx
"use client";

import { apiBaseUrl } from "@/lib/runtime-config";
import { useState } from "react";
import { authHeaders } from "@/lib/auth-session";
import type { RepositoryCompare } from "@/lib/api";

const API_URL = apiBaseUrl();

type SyncForkButtonProps = {
  owner: string;
  name: string;
  disabled?: boolean;
};

export function SyncForkButton({ owner, name, disabled = false }: SyncForkButtonProps) {
  const [message, setMessage] = useState("");
  const [isSyncing, setIsSyncing] = useState(false);

  async function sync() {
    setIsSyncing(true);
    setMessage("");
    const response = await fetch(`${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/sync-upstream`, {
      method: "POST",
      headers: authHeaders(),
    });
    setIsSyncing(false);

    if (!response.ok) {
      setMessage(`Sync failed: ${response.status}`);
      return;
    }

    const body = (await response.json()) as RepositoryCompare;
    setMessage(body.behind_by === 0 ? "Fork synced." : "Sync completed with remaining differences.");
    window.location.reload();
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <button
        className="cursor-pointer rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60"
        disabled={disabled || isSyncing}
        type="button"
        onClick={sync}
      >
        {isSyncing ? "Syncing..." : "Sync fork"}
      </button>
      {message ? <span className="text-sm text-[#59636e]">{message}</span> : null}
    </div>
  );
}

// apps/qwik-web/src/components/repository/SyncForkButton.tsx
import { $, component$, useSignal } from "@builder.io/qwik";

import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl, type RepositoryCompare } from "~/lib/api";

type SyncForkButtonProps = {
  disabled?: boolean;
  name: string;
  owner: string;
};

export const SyncForkButton = component$(
  ({ disabled = false, name, owner }: SyncForkButtonProps) => {
    const message = useSignal("");
    const isSyncing = useSignal(false);

    const sync = $(async () => {
      const token = getAuthToken();
      if (!token) {
        message.value = "Sign in to sync this fork.";
        return;
      }

      isSyncing.value = true;
      message.value = "";
      const response = await fetch(
        `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/sync-upstream`,
        {
          method: "POST",
          headers: { authorization: `Bearer ${token}` },
        },
      );
      isSyncing.value = false;

      if (!response.ok) {
        message.value = `Sync failed: ${response.status}`;
        return;
      }

      const body = (await response.json()) as RepositoryCompare;
      message.value =
        body.behind_by === 0
          ? "Fork synced."
          : "Sync completed with remaining differences.";
      window.location.reload();
    });

    return (
      <div class="sync-fork-button">
        <button
          class="settings-resource-panel__primary-button"
          disabled={disabled || isSyncing.value}
          type="button"
          onClick$={sync}
        >
          {isSyncing.value ? "Syncing..." : "Sync fork"}
        </button>
        {message.value ? <span class="sync-fork-button__message">{message.value}</span> : null}
      </div>
    );
  },
);
