// apps/web/src/app/settings/layout.tsx
import Link from "next/link";

type UserSettingsLayoutProps = {
  children: React.ReactNode;
};

export default function UserSettingsLayout({ children }: UserSettingsLayoutProps) {
  return (
    <div className="grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]">
      <aside className="self-start rounded-md border border-[#d0d7de] bg-white">
        <nav aria-label="User settings" className="grid p-2">
          <SettingsLink href="/settings" label="General" />
          <SettingsLink href="/settings/keys" label="SSH keys" />
          <SettingsLink href="/settings/runners" label="Runners" />
          <SettingsLink href="/settings/oauth/applications" label="OAuth applications" />
          <SettingsLink href="/settings/oauth/tokens" label="OAuth tokens" />
        </nav>
      </aside>
      {children}
    </div>
  );
}

function SettingsLink({ href, label }: { href: string; label: string }) {
  return (
    <Link className="rounded-md px-3 py-2 font-semibold text-[#59636e] hover:bg-[#f6f8fa] hover:text-[#1f2328]" href={href}>
      {label}
    </Link>
  );
}

// apps/qwik-web/src/routes/settings/layout.tsx
import { Slot, component$ } from "@builder.io/qwik";
import { Link, useLocation } from "@builder.io/qwik-city";

export default component$(() => {
  return (
    <div class="settings-layout">
      <aside class="settings-layout__sidebar">
        <nav aria-label="User settings" class="settings-layout__nav">
          <SettingsLink href="/settings" label="General" />
          <SettingsLink href="/settings/keys" label="SSH keys" />
          <SettingsLink href="/settings/runners" label="Runners" />
          <SettingsLink
            href="/settings/oauth/applications"
            label="OAuth applications"
          />
          <SettingsLink href="/settings/oauth/tokens" label="OAuth tokens" />
        </nav>
      </aside>
      <section class="settings-layout__content">
        <Slot />
      </section>
    </div>
  );
});

const SettingsLink = component$(({ href, label }: { href: string; label: string }) => {
  const location = useLocation();

  return (
    <Link
      class={[
        "settings-layout__link",
        location.url.pathname === href ? "settings-layout__link--active" : "",
      ]}
      href={href}
    >
      {label}
    </Link>
  );
});
