// apps/qwik-web/src/routes/[owner]/[name]/settings/secrets/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { SecretsVariablesPanel } from "~/components/settings/SecretsVariablesPanel";
import {
  listRepositoryRunnerSecrets,
  listRepositoryRunnerVariables,
} from "~/lib/api";

export const useRepositorySecretsPage = routeLoader$(async ({ params }) => {
  const [secrets, variables] = await Promise.all([
    listRepositoryRunnerSecrets(params.owner, params.name).catch(() => ({ data: [] })),
    listRepositoryRunnerVariables(params.owner, params.name).catch(() => ({ data: [] })),
  ]);

  return {
    encodedName: encodeURIComponent(params.name),
    encodedOwner: encodeURIComponent(params.owner),
    secrets: secrets.data,
    variables: variables.data,
  };
});

export default component$(() => {
  const route = useRepositorySecretsPage();

  return (
    <SecretsVariablesPanel
      scopeLabel="repository"
      secrets={route.value.secrets}
      secretsPath={`/repos/${route.value.encodedOwner}/${route.value.encodedName}/actions/secrets`}
      variables={route.value.variables}
      variablesPath={`/repos/${route.value.encodedOwner}/${route.value.encodedName}/actions/variables`}
    />
  );
});

// apps/web/src/app/[owner]/[name]/settings/secrets/page.tsx
import { SecretsVariablesPanel } from "@/components/SecretsVariablesPanel";
import { listRepositoryRunnerSecrets, listRepositoryRunnerVariables } from "@/lib/api";

type Props = {
  params: Promise<{ owner: string; name: string }>;
};

export default async function RepositorySecretsPage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const [secrets, variables] = await Promise.all([
    listRepositoryRunnerSecrets(decodedOwner, decodedName).catch(() => ({ data: [] })),
    listRepositoryRunnerVariables(decodedOwner, decodedName).catch(() => ({ data: [] })),
  ]);
  const encodedOwner = encodeURIComponent(decodedOwner);
  const encodedName = encodeURIComponent(decodedName);

  return (
    <SecretsVariablesPanel
      scopeLabel="repository"
      secrets={secrets.data}
      secretsPath={`/repos/${encodedOwner}/${encodedName}/actions/secrets`}
      variables={variables.data}
      variablesPath={`/repos/${encodedOwner}/${encodedName}/actions/variables`}
    />
  );
}
