// apps/web/src/app/[owner]/[name]/blob/[...path]/page.tsx
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { RepositoryCodeBrowser } from "@/components/RepositoryCodeBrowser";
import {
  getRepository,
  getRepositoryFile,
  getRepositoryTree,
  listPullRequests,
  listRepositoryBranches,
  listRepositoryTags,
  type RepositoryTree,
} from "@/lib/api";

type Props = {
  params: Promise<{ owner: string; name: string; path: string[] }>;
  searchParams: Promise<{ ref?: string }>;
};

export default async function RepositoryBlobPage({ params, searchParams }: Props) {
  const { owner, name, path } = await params;
  const { ref } = await searchParams;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const filePath = path.map(decodeURIComponent).join("/");
  const parentPath = path.length > 1 ? path.slice(0, -1).map(decodeURIComponent).join("/") : undefined;
  const repo = await getRepository(decodedOwner, decodedName);
  const selectedRef = ref || repo.default_branch;
  const baseHref = repoHref(decodedOwner, decodedName);
  const [pullRequests, branches, tags, tree, fullTree, file] = await Promise.all([
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [] })),
    listRepositoryBranches(decodedOwner, decodedName).catch(() => ({
      data: [{ name: repo.default_branch, is_default: true, commit_sha: null }],
    })),
    listRepositoryTags(decodedOwner, decodedName).catch(() => ({ data: [] })),
    getRepositoryTree(decodedOwner, decodedName, selectedRef, parentPath).catch(
      (): RepositoryTree => ({ ref_name: selectedRef, last_commit: null, entries: [] }),
    ),
    getRepositoryTree(decodedOwner, decodedName, selectedRef, undefined, true).catch(
      (): RepositoryTree => ({ ref_name: selectedRef, last_commit: null, entries: [] }),
    ),
    getRepositoryFile(decodedOwner, decodedName, filePath, selectedRef),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="code" pullRequestsCount={pullRequests.data.length} repo={repo} />
      <RepoPageContent>
        <RepositoryCodeBrowser
          baseHref={baseHref}
          branches={branches.data}
          currentPath={filePath}
          file={file}
          fullTree={fullTree}
          mode="blob"
          owner={decodedOwner}
          repo={repo}
          selectedRef={selectedRef}
          tags={tags.data}
          tree={tree}
        />
      </RepoPageContent>
    </div>
  );
}

// apps/qwik-web/src/routes/[owner]/[name]/blob/[...path]/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";
import {
  PrivateRepositoryNotFound,
} from "~/components/repository/PrivateRepositoryNotFound";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import { RepositoryCodeBrowser } from "~/components/repository/code/RepositoryCodeBrowser";
import { authTokenFromCookie } from "~/lib/server-auth";
import {
  decodeCodeBrowserPath,
  loadRepositoryCodeBrowser,
} from "../../code-browser";

export const useRepositoryBlobRoute = routeLoader$(async ({ cookie, params, url }) => {
  return loadRepositoryCodeBrowser(params.owner, params.name, {
    authToken: authTokenFromCookie(cookie),
    currentPath: decodeCodeBrowserPath(params.path),
    mode: "blob",
    query: url.searchParams.get("q")?.trim() ?? "",
    ref: url.searchParams.get("ref"),
  });
});

export default component$(() => {
  const route = useRepositoryBlobRoute();

  if (!route.value.repository) {
    return <PrivateRepositoryNotFound />;
  }

  const repository = route.value.repository;
  const baseHref = `/${encodeURIComponent(repository.owner_handle)}/${encodeURIComponent(
    repository.name,
  )}`;

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="code"
        pullRequestsCount={route.value.pullRequestsCount}
        repo={repository}
      />
      <RepoPageContent>
        <RepositoryCodeBrowser
          baseHref={baseHref}
          branches={route.value.branches}
          currentPath={route.value.currentPath}
          file={route.value.file}
          fullTree={route.value.fullTree}
          mode="blob"
          query={route.value.query}
          repo={repository}
          selectedRef={route.value.selectedRef}
          tags={route.value.tags}
          tree={route.value.tree}
        />
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Repository File · Diggit",
};
