// apps/qwik-web/src/routes/admin/runners/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { RunnerPanel } from "~/components/settings/RunnerPanel";

export default component$(() => {
  return (
    <div class="admin-page">
      <section class="admin-page__hero">
        <p class="admin-page__eyebrow">Admin / Runners</p>
        <h1 class="admin-page__title">Server runners</h1>
        <p class="admin-page__description">
          Manage server-scope Gitea-compatible runners.
        </p>
      </section>
      <RunnerPanel
        listPath="/admin/actions/runners"
        scopeLabel="Server"
        tokenPath="/admin/actions/runners/registration-token"
      />
    </div>
  );
});

export const head: DocumentHead = {
  title: "Server Runners · Diggit",
};

// apps/web/src/app/admin/runners/page.tsx
import { RunnerPanel } from "@/components/RunnerPanel";

export default function AdminRunnersPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          Admin / Runners
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">Server runners</h1>
        <p className="text-[#59636e]">Manage server-scope Gitea-compatible runners.</p>
      </section>
      <RunnerPanel
        listPath="/admin/actions/runners"
        scopeLabel="Server"
        tokenPath="/admin/actions/runners/registration-token"
      />
    </div>
  );
}
