// apps/web/src/app/organizations/[org]/repositories/page.tsx
import { NewRepositoryButton } from "@/components/NewRepositoryButton";
import { RepositoryList } from "@/components/RepositoryList";
import { getOrganization, listOrganizationRepositories } from "@/lib/api";

type OrganizationRepositoriesPageProps = {
  params: Promise<{
    org: string;
  }>;
  searchParams: Promise<{
    q?: string;
    sort?: string;
    direction?: string;
  }>;
};

export default async function OrganizationRepositoriesPage({ params, searchParams }: OrganizationRepositoriesPageProps) {
  const { org } = await params;
  const filters = await searchParams;
  const [organization, repos] = await Promise.all([
    getOrganization(org),
    listOrganizationRepositories(org, filters).catch(() => ({ data: [] })),
  ]);

  return (
    <main className="grid gap-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 className="text-xl font-semibold">Repositories</h2>
        <NewRepositoryButton owner={organization.name} organizationCreatorId={organization.created_by} />
      </div>
      <RepoFilters q={filters.q} sort={filters.sort} direction={filters.direction} />
      <RepositoryList emptyLabel="No repositories matched this organization." repositories={repos.data} />
    </main>
  );
}

function RepoFilters({ q = "", sort = "updated", direction = "desc" }: { q?: string; sort?: string; direction?: string }) {
  return (
    <form className="flex flex-col gap-3 rounded-md border border-[#d0d7de] bg-white p-3 md:flex-row">
      <input className="min-w-0 flex-1 rounded-md border border-[#d0d7de] px-3 py-2" defaultValue={q} name="q" placeholder="Find a repository..." type="search" />
      <select className="rounded-md border border-[#d0d7de] px-3 py-2" defaultValue={sort} name="sort">
        <option value="updated">Last updated</option>
        <option value="stars">Stars</option>
        <option value="name">Name</option>
      </select>
      <select className="rounded-md border border-[#d0d7de] px-3 py-2" defaultValue={direction} name="direction">
        <option value="desc">Descending</option>
        <option value="asc">Ascending</option>
      </select>
      <button className="rounded-md border border-[#d0d7de] bg-[#f6f8fa] px-3 py-2 font-semibold" type="submit">
        Filter
      </button>
    </form>
  );
}

// apps/qwik-web/src/routes/organizations/[org]/repositories/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";
import { RepositoryList } from "~/components/repositories/RepositoryList";
import { NewRepositoryButton } from "~/components/users/NewRepositoryButton";
import {
  getOrganization,
  listOrganizationRepositories,
} from "~/lib/api";

export const useOrganizationRepositoriesRoute = routeLoader$(
  async ({ params, url }) => {
    const filters = {
      q: url.searchParams.get("q")?.trim() ?? "",
      sort: url.searchParams.get("sort")?.trim() ?? "updated",
      direction: url.searchParams.get("direction")?.trim() ?? "desc",
    };
    const [organization, repos] = await Promise.all([
      getOrganization(params.org),
      listOrganizationRepositories(params.org, filters).catch(() => ({ data: [] })),
    ]);

    return {
      filters,
      organization,
      repos: repos.data,
    };
  },
);

export default component$(() => {
  const route = useOrganizationRepositoriesRoute();
  const { filters, organization, repos } = route.value;

  return (
    <main class="organization-repositories-page">
      <div class="organization-repositories-page__header">
        <h2 class="organization-repositories-page__title">Repositories</h2>
        <NewRepositoryButton
          organizationCreatorId={organization.created_by}
          owner={organization.name}
        />
      </div>
      <form class="user-profile-filters">
        <input
          class="user-profile-filters__input"
          defaultValue={filters.q}
          name="q"
          placeholder="Find a repository..."
          type="search"
        />
        <select class="user-profile-filters__select" name="sort">
          <option selected={filters.sort === "updated"} value="updated">
            Last updated
          </option>
          <option selected={filters.sort === "stars"} value="stars">
            Stars
          </option>
          <option selected={filters.sort === "name"} value="name">
            Name
          </option>
        </select>
        <select class="user-profile-filters__select" name="direction">
          <option selected={filters.direction === "desc"} value="desc">
            Descending
          </option>
          <option selected={filters.direction === "asc"} value="asc">
            Ascending
          </option>
        </select>
        <button class="user-profile-filters__submit" type="submit">
          Filter
        </button>
      </form>
      <RepositoryList
        emptyLabel="No repositories matched this organization."
        repositories={repos}
      />
    </main>
  );
});

export const head: DocumentHead = {
  title: "Organization Repositories · Diggit",
};
