// apps/web/src/app/[owner]/[name]/releases/page.tsx
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { RepositoryReleasesPanel } from "@/components/RepositoryReleasesPanel";
import { getRepository, listPullRequests, listReleases, listRepositoryTags, type Release } from "@/lib/api";
import { getReleaseSearchInput, parseReleaseSearchQuery } from "@/lib/repo-list-query";

type Props = {
  params: Promise<{
    owner: string;
    name: string;
  }>;
  searchParams: Promise<{
    page?: string;
    q?: string;
    status?: string;
  }>;
};

export default async function RepositoryReleasesPage({ params, searchParams }: Props) {
  const { owner, name } = await params;
  const { page, q, status: rawStatus } = await searchParams;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const baseHref = repoHref(decodedOwner, decodedName);
  const status = releaseStatus(rawStatus);
  const query = getReleaseSearchInput(q);
  const parsedQuery = parseReleaseSearchQuery(query);
  const selectedPage = Number.parseInt(page ?? "1", 10) || 1;
  const [repo, pullRequests, releases, releaseCount, tags] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [], pagination: { page: 1, limit: 1, total: 0, totalPages: 0 } })),
    listReleases(decodedOwner, decodedName, {
      page: selectedPage,
      limit: 25,
      prerelease: parsedQuery.isPrerelease || undefined,
      q: parsedQuery.searchText || undefined,
      status,
      tag: parsedQuery.tag || undefined,
    }).catch(() => emptyReleases(selectedPage)),
    listReleases(decodedOwner, decodedName, { page: 1, limit: 1, status: "published" }).catch(() => emptyReleases(1)),
    listRepositoryTags(decodedOwner, decodedName).catch(() => ({ data: [] })),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="releases" pullRequestsCount={pullRequests.pagination?.total ?? pullRequests.data.length} releasesCount={releaseCount.pagination.total} repo={repo} />

      <RepoPageContent>
        <RepositoryReleasesPanel
          baseHref={baseHref}
          name={decodedName}
          owner={decodedOwner}
          pagination={releases.pagination}
          query={query}
          releases={releases.data}
          status={status}
          tags={tags.data}
        />
      </RepoPageContent>
    </div>
  );
}

function releaseStatus(value?: string): "published" | "draft" | "all" {
  return value === "draft" || value === "all" ? value : "published";
}

function emptyReleases(page: number) {
  return {
    data: [] as Release[],
    pagination: {
      page,
      limit: 25,
      total: 0,
      totalPages: 0,
    },
  };
}

// apps/qwik-web/src/routes/[owner]/[name]/releases/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { RepositoryReleasesPanel } from "~/components/releases/RepositoryReleasesPanel";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import {
  getRepository,
  listPullRequests,
  listReleases,
  listRepositoryTags,
  type Release,
} from "~/lib/api";
import {
  getReleaseSearchInput,
  parseReleaseSearchQuery,
} from "~/lib/repo-list-query";

export const useRepositoryReleasesPage = routeLoader$(async ({ params, url }) => {
  const page = url.searchParams.get("page") ?? undefined;
  const q = url.searchParams.get("q") ?? undefined;
  const rawStatus = url.searchParams.get("status") ?? undefined;
  const status = releaseStatus(rawStatus);
  const query = getReleaseSearchInput(q);
  const parsedQuery = parseReleaseSearchQuery(query);
  const selectedPage = Number.parseInt(page ?? "1", 10) || 1;

  const [repo, pullRequests, releases, releaseCount, tags] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    listReleases(params.owner, params.name, {
      page: selectedPage,
      limit: 25,
      prerelease: parsedQuery.isPrerelease || undefined,
      q: parsedQuery.searchText || undefined,
      status,
      tag: parsedQuery.tag || undefined,
    }).catch(() => emptyReleases(selectedPage)),
    listReleases(params.owner, params.name, {
      page: 1,
      limit: 1,
      status: "published",
    }).catch(() => emptyReleases(1)),
    listRepositoryTags(params.owner, params.name).catch(() => ({ data: [] })),
  ]);

  return {
    baseHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}`,
    name: params.name,
    owner: params.owner,
    pagination: releases.pagination,
    pullRequestsCount: pullRequests.pagination.total,
    query,
    releases: releases.data,
    releasesCount: releaseCount.pagination.total,
    repo,
    status,
    tags: tags.data,
  };
});

export default component$(() => {
  const route = useRepositoryReleasesPage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="releases"
        pullRequestsCount={route.value.pullRequestsCount}
        releasesCount={route.value.releasesCount}
        repo={route.value.repo}
      />
      <RepoPageContent>
        <RepositoryReleasesPanel
          baseHref={route.value.baseHref}
          name={route.value.name}
          owner={route.value.owner}
          pagination={route.value.pagination}
          query={route.value.query}
          releases={route.value.releases}
          status={route.value.status}
          tags={route.value.tags}
        />
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Releases · Diggit",
};

function releaseStatus(value?: string): "published" | "draft" | "all" {
  return value === "draft" || value === "all" ? value : "published";
}

function emptyReleases(page: number) {
  return {
    data: [] as Release[],
    pagination: {
      page,
      limit: 25,
      total: 0,
      totalPages: 0,
    },
  };
}
