// apps/web/src/app/[owner]/[name]/settings/webhooks/page.tsx
import { RepositoryWebhooksPanel } from "@/components/RepositoryWebhooksPanel";

type RepositoryWebhooksPageProps = {
  params: Promise<{
    owner: string;
    name: string;
  }>;
};

export default async function RepositoryWebhooksPage({ params }: RepositoryWebhooksPageProps) {
  const { owner, name } = await params;
  return <RepositoryWebhooksPanel name={decodeURIComponent(name)} owner={decodeURIComponent(owner)} />;
}

// apps/qwik-web/src/routes/[owner]/[name]/settings/webhooks/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { RepositoryWebhooksPanel } from "~/components/settings/RepositoryWebhooksPanel";

export const useRepositoryWebhooksPage = routeLoader$(({ params }) => {
  return {
    name: params.name,
    owner: params.owner,
  };
});

export default component$(() => {
  const route = useRepositoryWebhooksPage();

  return (
    <RepositoryWebhooksPanel
      name={route.value.name}
      owner={route.value.owner}
    />
  );
});
