// apps/web/src/app/[owner]/[name]/settings/layout.tsx
import Link from "next/link";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { getRepository, listPullRequests } from "@/lib/api";

type RepositorySettingsLayoutProps = {
  children: React.ReactNode;
  params: Promise<{
    owner: string;
    name: string;
  }>;
};

export default async function RepositorySettingsLayout({ children, params }: RepositorySettingsLayoutProps) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const settingsHref = `${repoHref(decodedOwner, decodedName)}/settings`;
  const [repo, pullRequests] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [], pagination: { page: 1, limit: 1, total: 0, totalPages: 0 } })),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="settings" pullRequestsCount={pullRequests.pagination?.total ?? pullRequests.data.length} repo={repo} />
      <RepoPageContent>
        <div className="grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]">
          <aside className="self-start rounded-md border border-[#d0d7de] bg-white">
            <nav aria-label="Repository settings" className="grid p-2">
              <SettingsLink href={settingsHref} label="General" />
              <SettingsLink href={`${settingsHref}/collaborators`} label="Collaborators" />
              <SettingsLink href={`${settingsHref}/secrets`} label="Secrets and variables" />
              <SettingsLink href={`${settingsHref}/webhooks`} label="Webhooks" />
            </nav>
          </aside>
          {children}
        </div>
      </RepoPageContent>
    </div>
  );
}

function SettingsLink({ href, label }: { href: string; label: string }) {
  return (
    <Link className="rounded-md px-3 py-2 font-semibold text-[#59636e] hover:bg-[#f6f8fa] hover:text-[#1f2328]" href={href}>
      {label}
    </Link>
  );
}

// apps/qwik-web/src/routes/[owner]/[name]/settings/layout.tsx
import { Slot, component$ } from "@builder.io/qwik";
import {
  Link,
  type DocumentHead,
  routeLoader$,
  useLocation,
} from "@builder.io/qwik-city";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import { getRepository, listPullRequests } from "~/lib/api";

export const useRepositorySettingsLayout = routeLoader$(async ({ params }) => {
  const [repo, pullRequests] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
  ]);

  return {
    pullRequestsCount: pullRequests.pagination?.total ?? pullRequests.data.length,
    repo,
    settingsHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}/settings`,
  };
});

export default component$(() => {
  const layout = useRepositorySettingsLayout();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="settings"
        pullRequestsCount={layout.value.pullRequestsCount}
        repo={layout.value.repo}
      />
      <RepoPageContent>
        <div class="settings-layout">
          <aside class="settings-layout__sidebar">
            <nav aria-label="Repository settings" class="settings-layout__nav">
              <SettingsLink href={layout.value.settingsHref} label="General" />
              <SettingsLink
                href={`${layout.value.settingsHref}/collaborators`}
                label="Collaborators"
              />
              <SettingsLink
                href={`${layout.value.settingsHref}/secrets`}
                label="Secrets and variables"
              />
              <SettingsLink
                href={`${layout.value.settingsHref}/webhooks`}
                label="Webhooks"
              />
              <SettingsLink
                href={`${layout.value.settingsHref}/runners`}
                label="Runners"
              />
            </nav>
          </aside>
          <section class="settings-layout__content">
            <Slot />
          </section>
        </div>
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Repository Settings · Diggit",
};

const SettingsLink = component$(({ href, label }: { href: string; label: string }) => {
  const location = useLocation();

  return (
    <Link
      class={[
        "settings-layout__link",
        location.url.pathname === href ? "settings-layout__link--active" : "",
      ]}
      href={href}
    >
      {label}
    </Link>
  );
});
