// apps/qwik-web/src/components/repository/code/FileEditor.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { useNavigate } from "@builder.io/qwik-city";

import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type FileEditorProps = {
  content: string;
  name: string;
  owner: string;
  path: string;
  redirectTo: string;
};

export const FileEditor = component$(
  ({ content, name, owner, path, redirectTo }: FileEditorProps) => {
    const nav = useNavigate();
    const message = useSignal("");
    const isSaving = useSignal(false);
    const commitMessage = useSignal("");
    const fileContent = useSignal(content);

    const submit = $(async () => {
      const token = getAuthToken();
      if (!token) {
        message.value = "Sign in to edit";
        return;
      }

      const params = new URLSearchParams({ path });

      isSaving.value = true;
      message.value = "";

      const response = await fetch(
        `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/contents?${params.toString()}`,
        {
          method: "PUT",
          headers: {
            authorization: `Bearer ${token}`,
            "content-type": "application/json",
          },
          body: JSON.stringify({
            content: fileContent.value,
            message: commitMessage.value.trim() || undefined,
          }),
        },
      );

      isSaving.value = false;

      if (!response.ok) {
        message.value = `Failed: ${response.status}`;
        return;
      }

      await nav(redirectTo);
    });

    return (
      <form class="file-editor" onSubmit$={submit} preventdefault:submit>
        <label class="pull-request-flow__field">
          Commit message
          <input
            class="settings-drawer-form__input"
            placeholder={`Update ${path}`}
            value={commitMessage.value}
            onInput$={(_, currentTarget) => {
              commitMessage.value = currentTarget.value;
            }}
          />
        </label>

        <label class="pull-request-flow__field">
          File content
          <textarea
            class="file-editor__textarea"
            name="content"
            value={fileContent.value}
            onInput$={(_, currentTarget) => {
              fileContent.value = currentTarget.value;
            }}
          />
        </label>

        <div class="file-editor__actions">
          <button
            class="settings-resource-panel__primary-button"
            disabled={isSaving.value}
            type="submit"
          >
            {isSaving.value ? "Saving..." : "Commit changes"}
          </button>
          {message.value ? <span class="issue-detail-page__meta">{message.value}</span> : null}
        </div>
      </form>
    );
  },
);

// apps/web/src/components/FileEditor.tsx
"use client";

import { apiBaseUrl } from "@/lib/runtime-config";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { getAuthToken } from "@/lib/auth-session";

const API_URL = apiBaseUrl();

type FileEditorProps = {
  content: string;
  name: string;
  owner: string;
  path: string;
  redirectTo: string;
};

export function FileEditor({ content, name, owner, path, redirectTo }: FileEditorProps) {
  const router = useRouter();
  const [message, setMessage] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const token = getAuthToken();
    if (!token) {
      setMessage("Sign in to edit");
      return;
    }

    const form = new FormData(event.currentTarget);
    const params = new URLSearchParams({ path });

    setIsSaving(true);
    setMessage("");

    const response = await fetch(
      `${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/contents?${params.toString()}`,
      {
        method: "PUT",
        headers: {
          authorization: `Bearer ${token}`,
          "content-type": "application/json",
        },
        body: JSON.stringify({
          content: String(form.get("content") ?? ""),
          message: String(form.get("message") ?? "").trim() || undefined,
        }),
      },
    );

    setIsSaving(false);

    if (!response.ok) {
      setMessage(`Failed: ${response.status}`);
      return;
    }

    router.push(redirectTo);
    router.refresh();
  }

  return (
    <form className="grid gap-4" onSubmit={submit}>
      <label className="grid gap-1.5">
        Commit message
        <input
          className="w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2 text-[#1f2328]"
          name="message"
          placeholder={`Update ${path}`}
        />
      </label>

      <label className="grid gap-1.5">
        File content
        <textarea
          className="min-h-[560px] w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2 font-mono text-sm leading-6 text-[#1f2328]"
          defaultValue={content}
          name="content"
        />
      </label>

      <div className="flex flex-wrap items-center gap-3">
        <button
          className="cursor-pointer rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white hover:bg-[#116329]"
          disabled={isSaving}
          type="submit"
        >
          {isSaving ? "Saving..." : "Commit changes"}
        </button>
        {message ? <span className="text-[#59636e]">{message}</span> : null}
      </div>
    </form>
  );
}
