// apps/qwik-web/src/components/organizations/OrganizationFollowButton.tsx
import { $, component$, useSignal } from "@builder.io/qwik";

export const OrganizationFollowButton = component$(() => {
  const isFollowing = useSignal(false);

  return (
    <button
      aria-pressed={isFollowing.value}
      class="organization-follow-button"
      type="button"
      onClick$={$(() => {
        isFollowing.value = !isFollowing.value;
      })}
    >
      {isFollowing.value ? "Following" : "Follow"}
    </button>
  );
});

// apps/web/src/components/OrganizationFollowButton.tsx
"use client";

import { useState } from "react";

export function OrganizationFollowButton() {
  const [isFollowing, setIsFollowing] = useState(false);

  return (
    <button
      aria-pressed={isFollowing}
      className="cursor-pointer rounded-md border border-[#d0d7de] bg-[#f6f8fa] px-3 py-1.5 font-semibold hover:border-[#0969da] hover:text-[#0969da]"
      type="button"
      onClick={() => setIsFollowing((value) => !value)}
    >
      {isFollowing ? "Following" : "Follow"}
    </button>
  );
}
