// apps/qwik-web/src/components/settings/SshKeysPanel.tsx
import { $, component$, isBrowser, useSignal, useTask$ } from "@builder.io/qwik";
import { Drawer } from "~/components/ui/Drawer";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type SshKey = {
  id: string;
  title: string;
  fingerprint: string;
  created_at: string;
};

export const SshKeysPanel = component$(() => {
  const keys = useSignal<SshKey[]>([]);
  const message = useSignal("");
  const isAddKeyOpen = useSignal(false);

  const loadKeys = $(async () => {
    const token = getAuthToken();
    if (!token) {
      keys.value = [];
      message.value = "Sign in to manage SSH keys.";
      return;
    }

    const response = await fetch(`${publicApiBaseUrl()}/user/keys`, {
      headers: { authorization: `Bearer ${token}` },
    });
    if (!response.ok) {
      message.value = `Failed to load keys: ${response.status}`;
      return;
    }

    const body = (await response.json()) as { data: SshKey[] };
    keys.value = body.data;
    message.value = "";
  });

  useTask$(async () => {
    if (!isBrowser || !getAuthToken()) {
      return;
    }
    await loadKeys();
  });

  const submit = $(async (_event: SubmitEvent, formElement: HTMLFormElement) => {
    const token = getAuthToken();
    if (!token) {
      message.value = "Sign in to add SSH keys.";
      return;
    }

    const form = new FormData(formElement);
    const response = await fetch(`${publicApiBaseUrl()}/user/keys`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        title: form.get("title"),
        public_key: form.get("publicKey"),
      }),
    });

    if (!response.ok) {
      message.value = `Failed to add SSH key: ${response.status}`;
      return;
    }

    message.value = "SSH key added.";
    formElement.reset();
    isAddKeyOpen.value = false;
    await loadKeys();
  });

  const removeKey = $(async (id: string) => {
    const token = getAuthToken();
    if (!token) {
      message.value = "Sign in to remove SSH keys.";
      return;
    }

    await fetch(`${publicApiBaseUrl()}/user/keys/${id}`, {
      method: "DELETE",
      headers: { authorization: `Bearer ${token}` },
    });
    await loadKeys();
  });

  return (
    <section class="settings-resource-panel">
      <div class="settings-resource-panel__header">
        <strong>SSH keys</strong>
        <div class="settings-resource-panel__actions">
          <button
            class="settings-resource-panel__secondary-button"
            type="button"
            onClick$={loadKeys}
          >
            Refresh
          </button>
          <button
            class="settings-resource-panel__primary-button"
            type="button"
            onClick$={() => {
              isAddKeyOpen.value = true;
            }}
          >
            Add key
          </button>
        </div>
      </div>

      <Drawer
        isOpen={isAddKeyOpen.value}
        onClose$={$(() => {
          isAddKeyOpen.value = false;
        })}
        subtitle="SSH keys"
        title="Add SSH key"
      >
        <form
          class="settings-drawer-form"
          onSubmit$={submit}
          preventdefault:submit
        >
          <label class="settings-drawer-form__label">
            Title
            <input class="settings-drawer-form__input" name="title" required />
          </label>
          <label class="settings-drawer-form__label">
            Public key
            <textarea
              class="settings-drawer-form__textarea"
              name="publicKey"
              required
            />
          </label>
          <div class="settings-drawer-form__actions">
            <button
              class="settings-resource-panel__secondary-button"
              type="button"
              onClick$={() => {
                isAddKeyOpen.value = false;
              }}
            >
              Cancel
            </button>
            <button class="settings-resource-panel__primary-button" type="submit">
              Add key
            </button>
          </div>
        </form>
      </Drawer>

      {message.value ? (
        <div class="settings-resource-panel__message">{message.value}</div>
      ) : null}
      <div class="settings-resource-panel__body">
        {keys.value.length === 0 ? (
          <div class="settings-resource-panel__empty">
            No keys loaded yet. Refresh after signing in.
          </div>
        ) : (
          keys.value.map((key) => (
            <article class="settings-resource-item" key={key.id}>
              <strong>{key.title}</strong>
              <span class="settings-resource-item__mono">{key.fingerprint}</span>
              <button
                class="settings-resource-item__delete"
                type="button"
                onClick$={() => removeKey(key.id)}
              >
                Delete
              </button>
            </article>
          ))
        )}
      </div>
    </section>
  );
});

// apps/web/src/components/SshKeysPanel.tsx
"use client";

import { apiBaseUrl } from "@/lib/runtime-config";
import { FormEvent, useEffect, useRef, useState } from "react";
import { authHeaders, getAuthToken } from "@/lib/auth-session";

const API_URL = apiBaseUrl();

type SshKey = {
  id: string;
  title: string;
  fingerprint: string;
  created_at: string;
};

export function SshKeysPanel() {
  const [keys, setKeys] = useState<SshKey[]>([]);
  const [message, setMessage] = useState("");
  const [isAddKeyOpen, setIsAddKeyOpen] = useState(false);
  const titleInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!isAddKeyOpen) {
      return;
    }

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    titleInputRef.current?.focus();

    function closeOnEscape(event: KeyboardEvent) {
      if (event.key === "Escape") {
        setIsAddKeyOpen(false);
      }
    }

    window.addEventListener("keydown", closeOnEscape);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", closeOnEscape);
    };
  }, [isAddKeyOpen]);

  useEffect(() => {
    if (!getAuthToken()) {
      return;
    }
    void loadKeys();
  }, []);

  async function loadKeys() {
    const response = await fetch(`${API_URL}/user/keys`, { headers: authHeaders() });
    if (!response.ok) {
      setMessage(`Failed to load keys: ${response.status}`);
      return;
    }

    const body = (await response.json()) as { data: SshKey[] };
    setKeys(body.data);
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formElement = event.currentTarget;
    const form = new FormData(formElement);
    const response = await fetch(`${API_URL}/user/keys`, {
      method: "POST",
      headers: { "content-type": "application/json", ...authHeaders() },
      body: JSON.stringify({
        title: form.get("title"),
        public_key: form.get("publicKey"),
      }),
    });

    if (!response.ok) {
      setMessage(`Failed to add SSH key: ${response.status}`);
      return;
    }

    setMessage("SSH key added.");
    formElement.reset();
    setIsAddKeyOpen(false);
    await loadKeys();
  }

  async function removeKey(id: string) {
    await fetch(`${API_URL}/user/keys/${id}`, {
      method: "DELETE",
      headers: authHeaders(),
    });
    await loadKeys();
  }

  return (
    <section className="rounded-md border border-[#d0d7de] bg-white">
      <div className="flex flex-wrap items-center justify-between gap-2 rounded-t-md border-b border-[#d0d7de] bg-[#f6f8fa] px-4 py-3">
        <strong>SSH keys</strong>
        <div className="flex gap-2">
          <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => void loadKeys()}>
            Refresh
          </button>
          <button className="rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white" type="button" onClick={() => setIsAddKeyOpen(true)}>
            Add key
          </button>
        </div>
      </div>
      {isAddKeyOpen ? (
        <div aria-labelledby="add-ssh-key-title" aria-modal="true" className="fixed inset-0 z-50 overflow-y-auto bg-white text-[#1f2328]" role="dialog">
          <div className="mx-auto grid min-h-dvh w-full max-w-4xl content-start gap-6 px-6 py-6 sm:px-10">
            <div className="flex items-start justify-between gap-4 border-b border-[#d8dee4] pb-4">
              <div>
                <p className="mb-1 text-[#59636e]">SSH keys</p>
                <h2 className="text-3xl font-semibold tracking-tight" id="add-ssh-key-title">
                  Add SSH key
                </h2>
              </div>
              <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => setIsAddKeyOpen(false)}>
                Close
              </button>
            </div>
            <form className="grid gap-4 rounded-md border border-[#d0d7de] bg-[#f6f8fa] p-4 sm:p-6" onSubmit={submit}>
              <label className="grid gap-1.5">
                Title
                <input ref={titleInputRef} className="w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2" name="title" required />
              </label>
              <label className="grid gap-1.5">
                Public key
                <textarea className="min-h-40 w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2 font-mono" name="publicKey" required />
              </label>
              <div className="flex flex-wrap justify-end gap-2">
                <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => setIsAddKeyOpen(false)}>
                  Cancel
                </button>
                <button className="rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white" type="submit">
                  Add key
                </button>
              </div>
            </form>
          </div>
        </div>
      ) : null}
      {message ? <div className="border-b border-[#d8dee4] px-4 py-2 text-[#59636e]">{message}</div> : null}
      <div className="grid">
        {keys.length === 0 ? (
          <div className="p-4 text-[#59636e]">No keys loaded yet. Refresh after signing in.</div>
        ) : (
          keys.map((key) => (
            <article className="grid gap-2 border-b border-[#d8dee4] p-4 last:border-b-0" key={key.id}>
              <strong>{key.title}</strong>
              <span className="break-all font-mono text-[#59636e]">{key.fingerprint}</span>
              <button className="w-fit rounded-md border border-black/15 bg-white px-3 py-1.5 font-bold" type="button" onClick={() => void removeKey(key.id)}>
                Delete
              </button>
            </article>
          ))
        )}
      </div>
    </section>
  );
}
