// apps/web/src/components/CollaboratorsPanel.tsx
"use client";

import { Drawer } from "@/components/Drawer";
import { authHeaders, getAuthToken } from "@/lib/auth-session";
import type { Collaborator } from "@/lib/api";
import { apiBaseUrl } from "@/lib/runtime-config";
import { FormEvent, useEffect, useState } from "react";

const API_URL = apiBaseUrl();

type CollaboratorsPanelProps = {
  addPath: string;
  collaborators: Collaborator[];
  permissionName: "permission" | "role";
  scopeLabel: string;
};

export function CollaboratorsPanel({ addPath, collaborators, permissionName, scopeLabel }: CollaboratorsPanelProps) {
  const [items, setItems] = useState(collaborators);
  const [isOpen, setIsOpen] = useState(false);
  const [username, setUsername] = useState("");
  const [access, setAccess] = useState(permissionName === "role" ? "member" : "write");
  const [message, setMessage] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  const listPath = addPath;

  async function loadCollaborators() {
    const response = await fetch(`${API_URL}${listPath}`, {
      headers: authHeaders(),
    });
    if (!response.ok) {
      setMessage(`Unable to load collaborators. (${response.status})`);
      return;
    }
    const body = (await response.json()) as { data: Collaborator[] };
    setItems(body.data);
  }

  useEffect(() => {
    if (collaborators.length > 0) {
      return;
    }
    if (scopeLabel === "repository" && !getAuthToken()) {
      return;
    }
    void loadCollaborators();
  }, [collaborators.length, scopeLabel]);

  async function addCollaborator(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsSaving(true);
    setMessage("");
    const response = await fetch(`${API_URL}${addPath}`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        ...authHeaders(),
      },
      body: JSON.stringify({
        username,
        [permissionName]: access,
      }),
    });
    setIsSaving(false);
    if (!response.ok) {
      const body = (await response.json().catch(() => null)) as { error?: string } | null;
      setMessage(body?.error ?? "Unable to save collaborator.");
      return;
    }
    setUsername("");
    setIsOpen(false);
    await loadCollaborators();
  }

  return (
    <main className="grid gap-6">
      <section className="flex flex-wrap items-start justify-between gap-4">
        <div className="grid gap-2">
          <h2 className="text-2xl font-semibold tracking-tight">Collaborators</h2>
          <p className="text-[#59636e]">Manage who can access this {scopeLabel}.</p>
        </div>
        <button className="rounded-md border border-black/15 bg-[#1a7f37] px-4 py-2 font-bold text-white" type="button" onClick={() => setIsOpen(true)}>
          Add collaborator
        </button>
      </section>

      <section className="rounded-md border border-[#d0d7de] bg-white">
        {items.length === 0 ? (
          <p className="p-5 text-[#59636e]">No collaborators have been added yet.</p>
        ) : (
          <div className="grid">
            {items.map((collaborator) => (
              <article className="flex flex-wrap items-center justify-between gap-3 border-b border-[#d8dee4] p-5 last:border-b-0" key={collaborator.id}>
                <div>
                  <h3 className="font-semibold">{collaborator.display_name}</h3>
                  <p className="text-sm text-[#59636e]">@{collaborator.username}</p>
                </div>
                <span className="rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-sm font-semibold text-[#59636e]">
                  {collaborator[permissionName] ?? "member"}
                </span>
              </article>
            ))}
          </div>
        )}
      </section>

      <Drawer isOpen={isOpen} title="Add collaborator" onClose={() => setIsOpen(false)}>
        <form className="grid gap-4" onSubmit={addCollaborator}>
          <label className="grid gap-2">
            <span className="font-semibold">Username</span>
            <input className="max-w-md rounded-md border border-[#d0d7de] bg-white px-3 py-2" required value={username} onChange={(event) => setUsername(event.target.value)} />
          </label>
          <label className="grid gap-2">
            <span className="font-semibold">{permissionName === "role" ? "Role" : "Permission"}</span>
            <select className="max-w-md rounded-md border border-[#d0d7de] bg-white px-3 py-2" value={access} onChange={(event) => setAccess(event.target.value)}>
              {permissionName === "role" ? (
                <>
                  <option value="member">Member</option>
                  <option value="admin">Admin</option>
                  <option value="owner">Owner</option>
                </>
              ) : (
                <>
                  <option value="read">Read</option>
                  <option value="write">Write</option>
                  <option value="admin">Admin</option>
                </>
              )}
            </select>
          </label>
          <div className="flex items-center gap-3">
            <button className="w-fit rounded-md border border-black/15 bg-[#1a7f37] px-4 py-2 font-bold text-white disabled:opacity-60" disabled={isSaving} type="submit">
              {isSaving ? "Saving..." : "Save collaborator"}
            </button>
            {message ? <p className="text-sm text-[#59636e]">{message}</p> : null}
          </div>
        </form>
      </Drawer>
    </main>
  );
}

// apps/qwik-web/src/components/settings/CollaboratorsPanel.tsx
import { $, component$, isBrowser, useSignal, useTask$ } from "@builder.io/qwik";
import { Drawer } from "~/components/ui/Drawer";
import type { Collaborator } from "~/lib/api";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type CollaboratorsPanelProps = {
  addPath: string;
  collaborators: Collaborator[];
  permissionName: "permission" | "role";
  scopeLabel: string;
};

export const CollaboratorsPanel = component$(
  ({ addPath, collaborators, permissionName, scopeLabel }: CollaboratorsPanelProps) => {
    const items = useSignal(collaborators);
    const isOpen = useSignal(false);
    const username = useSignal("");
    const access = useSignal(permissionName === "role" ? "member" : "write");
    const message = useSignal("");
    const isSaving = useSignal(false);

    const loadCollaborators = $(async () => {
      const token = getAuthToken();
      if (scopeLabel === "repository" && !token) {
        return;
      }

      const response = await fetch(`${publicApiBaseUrl()}${addPath}`, {
        headers: token ? { authorization: `Bearer ${token}` } : undefined,
      });
      if (!response.ok) {
        message.value = `Unable to load collaborators. (${response.status})`;
        return;
      }
      const body = (await response.json()) as { data: Collaborator[] };
      items.value = body.data;
      message.value = "";
    });

    useTask$(async () => {
      if (!isBrowser) {
        return;
      }
      if (collaborators.length > 0) {
        return;
      }
      await loadCollaborators();
    });

    const addCollaborator = $(async () => {
      const token = getAuthToken();
      if (!token) {
        message.value = "Sign in to manage collaborators.";
        return;
      }

      isSaving.value = true;
      message.value = "";
      const response = await fetch(`${publicApiBaseUrl()}${addPath}`, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          username: username.value,
          [permissionName]: access.value,
        }),
      });
      isSaving.value = false;
      if (!response.ok) {
        const body = (await response.json().catch(() => null)) as
          | { error?: string }
          | null;
        message.value = body?.error ?? "Unable to save collaborator.";
        return;
      }
      username.value = "";
      isOpen.value = false;
      await loadCollaborators();
    });

    return (
      <main class="settings-group-page">
        <section class="settings-group-page__header">
          <div class="settings-group-page__copy">
            <h2 class="settings-group-page__title">Collaborators</h2>
            <p class="settings-group-page__description">
              Manage who can access this {scopeLabel}.
            </p>
          </div>
          <button
            class="settings-resource-panel__primary-button"
            type="button"
            onClick$={() => {
              isOpen.value = true;
            }}
          >
            Add collaborator
          </button>
        </section>

        <section class="settings-resource-panel">
          {items.value.length === 0 ? (
            <p class="settings-resource-panel__empty">
              No collaborators have been added yet.
            </p>
          ) : (
            <div class="settings-resource-panel__body">
              {items.value.map((collaborator) => (
                <article class="settings-resource-item settings-collaborator" key={collaborator.id}>
                  <div>
                    <h3 class="settings-collaborator__title">
                      {collaborator.display_name}
                    </h3>
                    <p class="settings-collaborator__handle">
                      @{collaborator.username}
                    </p>
                  </div>
                  <span class="runner-panel__pill">
                    {collaborator[permissionName] ?? "member"}
                  </span>
                </article>
              ))}
            </div>
          )}
        </section>

        <Drawer
          isOpen={isOpen.value}
          onClose$={$(() => {
            isOpen.value = false;
          })}
          title="Add collaborator"
        >
          <div class="settings-drawer-form">
            <label class="settings-drawer-form__label">
              <span class="settings-drawer-form__heading">Username</span>
              <input
                class="settings-drawer-form__input"
                required
                value={username.value}
                onInput$={(event) => {
                  username.value = (event.target as HTMLInputElement).value;
                }}
              />
            </label>
            <label class="settings-drawer-form__label">
              <span class="settings-drawer-form__heading">
                {permissionName === "role" ? "Role" : "Permission"}
              </span>
              <select
                class="settings-drawer-form__input"
                value={access.value}
                onChange$={(event) => {
                  access.value = (event.target as HTMLSelectElement).value;
                }}
              >
                {permissionName === "role" ? (
                  <>
                    <option value="member">Member</option>
                    <option value="admin">Admin</option>
                    <option value="owner">Owner</option>
                  </>
                ) : (
                  <>
                    <option value="read">Read</option>
                    <option value="write">Write</option>
                    <option value="admin">Admin</option>
                  </>
                )}
              </select>
            </label>
            <div class="settings-group-page__actions">
              <button
                class="settings-resource-panel__primary-button"
                disabled={isSaving.value}
                type="button"
                onClick$={addCollaborator}
              >
                {isSaving.value ? "Saving..." : "Save collaborator"}
              </button>
              {message.value ? (
                <p class="settings-group-page__message">{message.value}</p>
              ) : null}
            </div>
          </div>
        </Drawer>
      </main>
    );
  },
);
