// apps/web/src/components/OAuthApplicationsPanel.tsx
"use client";

import { Drawer } from "@/components/Drawer";
import { authHeaders, getAuthToken } from "@/lib/auth-session";
import { apiBaseUrl } from "@/lib/runtime-config";
import { FormEvent, useEffect, useState } from "react";

const API_URL = apiBaseUrl();

export type OAuthApplication = {
  id: string;
  client_id: string;
  name: string;
  redirect_uri: string;
  scopes: string[];
  created_at: string;
  updated_at: string;
};

type CreatedOAuthApplication = {
  application: OAuthApplication;
  client_secret: string;
};

export function OAuthApplicationsPanel({ initialApplications = [] }: { initialApplications?: OAuthApplication[] }) {
  const [applications, setApplications] = useState<OAuthApplication[]>(initialApplications);
  const [activeApplication, setActiveApplication] = useState<OAuthApplication | null>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [revealedSecret, setRevealedSecret] = useState<string | null>(null);

  async function loadApplications() {
    const response = await fetch(`${API_URL}/oauth/applications`, { headers: authHeaders() });
    if (!response.ok) {
      setMessage(`Failed to load OAuth applications: ${response.status}`);
      return;
    }
    const body = (await response.json()) as { data: OAuthApplication[] };
    setApplications(body.data);
  }

  useEffect(() => {
    if (initialApplications.length > 0 || !getAuthToken()) {
      return;
    }
    void loadApplications();
  }, [initialApplications.length]);

  async function createApplication(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formElement = event.currentTarget;
    const form = new FormData(formElement);
    const scopes = String(form.get("scopes") ?? "api read_user read_repository")
      .split(/\s+/)
      .map((scope) => scope.trim())
      .filter(Boolean);
    const response = await fetch(`${API_URL}/oauth/applications`, {
      method: "POST",
      headers: { "content-type": "application/json", ...authHeaders() },
      body: JSON.stringify({
        name: form.get("name"),
        redirect_uri: form.get("redirectUri"),
        scopes,
      }),
    });
    if (!response.ok) {
      setMessage(`Failed to create OAuth application: ${response.status}`);
      return;
    }
    const body = (await response.json()) as CreatedOAuthApplication;
    setRevealedSecret(body.client_secret);
    setActiveApplication(body.application);
    setMessage("OAuth application created. Copy the secret now; it will not be shown again.");
    formElement.reset();
    setIsCreateOpen(false);
    await loadApplications();
  }

  async function rotateSecret(application: OAuthApplication) {
    const response = await fetch(`${API_URL}/oauth/applications/${application.id}/rotate-secret`, {
      method: "POST",
      headers: authHeaders(),
    });
    if (!response.ok) {
      setMessage(`Failed to rotate secret: ${response.status}`);
      return;
    }
    const body = (await response.json()) as CreatedOAuthApplication;
    setRevealedSecret(body.client_secret);
    setActiveApplication(body.application);
    setMessage("Client secret rotated. Copy the new secret now.");
    await loadApplications();
  }

  async function deleteApplication(application: OAuthApplication) {
    const response = await fetch(`${API_URL}/oauth/applications/${application.id}`, {
      method: "DELETE",
      headers: authHeaders(),
    });
    if (!response.ok) {
      setMessage(`Failed to delete application: ${response.status}`);
      return;
    }
    setActiveApplication(null);
    setMessage("OAuth application deleted and its tokens revoked.");
    await loadApplications();
  }

  async function copy(value: string) {
    await navigator.clipboard.writeText(value);
    setMessage("Copied to clipboard.");
  }

  return (
    <section className="rounded-md border border-[#d0d7de] bg-white">
      <div className="flex flex-wrap items-center justify-between gap-2 rounded-t-md border-b border-[#d0d7de] bg-[#f6f8fa] px-4 py-3">
        <strong>OAuth applications</strong>
        <div className="flex gap-2">
          <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => void loadApplications()}>
            Refresh
          </button>
          <button className="rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white" type="button" onClick={() => setIsCreateOpen(true)}>
            New application
          </button>
        </div>
      </div>
      {message ? <div className="border-b border-[#d8dee4] px-4 py-2 text-[#59636e]">{message}</div> : null}
      <div className="grid">
        {applications.length === 0 ? (
          <div className="p-4 text-[#59636e]">No OAuth applications yet.</div>
        ) : (
          applications.map((application) => (
            <article className="grid gap-2 border-b border-[#d8dee4] p-4 last:border-b-0" key={application.id}>
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <strong>{application.name}</strong>
                  <p className="break-all text-sm text-[#59636e]">{application.redirect_uri}</p>
                </div>
                <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => setActiveApplication(application)}>
                  Manage
                </button>
              </div>
              <span className="text-sm text-[#59636e]">Scopes: {application.scopes.join(", ")}</span>
            </article>
          ))
        )}
      </div>

      <Drawer isOpen={isCreateOpen} title="New OAuth application" onClose={() => setIsCreateOpen(false)}>
        <form className="grid gap-4 rounded-md border border-[#d0d7de] bg-[#f6f8fa] p-4 sm:p-6" onSubmit={createApplication}>
          <label className="grid gap-1.5">
            Name
            <input className="w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2" name="name" placeholder="Dokploy" required />
          </label>
          <label className="grid gap-1.5">
            Redirect URI
            <input className="w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2" name="redirectUri" placeholder="https://your-dokploy-domain.com/api/providers/gitlab/callback" required />
          </label>
          <label className="grid gap-1.5">
            Scopes
            <input className="w-full rounded-md border border-[#d0d7de] bg-white px-3 py-2" name="scopes" defaultValue="api read_user read_repository" />
          </label>
          <button className="w-fit rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white" type="submit">
            Create application
          </button>
        </form>
      </Drawer>

      <Drawer isOpen={activeApplication !== null} title={activeApplication?.name ?? "OAuth application"} onClose={() => setActiveApplication(null)}>
        {activeApplication ? (
          <div className="grid gap-4">
            <InfoRow label="Application ID" value={activeApplication.client_id} onCopy={() => void copy(activeApplication.client_id)} />
            <InfoRow label="Redirect URI" value={activeApplication.redirect_uri} onCopy={() => void copy(activeApplication.redirect_uri)} />
            {revealedSecret ? <InfoRow label="Application Secret" value={revealedSecret} onCopy={() => void copy(revealedSecret)} /> : null}
            <div className="rounded-md border border-[#d0d7de] bg-[#f6f8fa] p-4">
              <p className="font-semibold">Dokploy setup</p>
              <p className="text-sm text-[#59636e]">
                Use this Diggit server as Dokploy&apos;s Gitlab URL, then paste the Application ID and Secret above.
              </p>
            </div>
            <div className="flex flex-wrap gap-2">
              <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => void rotateSecret(activeApplication)}>
                Rotate secret
              </button>
              <button className="rounded-md border border-[#cf222e] bg-white px-3 py-1.5 font-semibold text-[#cf222e]" type="button" onClick={() => void deleteApplication(activeApplication)}>
                Delete application
              </button>
            </div>
          </div>
        ) : null}
      </Drawer>
    </section>
  );
}

function InfoRow({ label, onCopy, value }: { label: string; onCopy: () => void; value: string }) {
  return (
    <div className="grid gap-2 rounded-md border border-[#d0d7de] p-3">
      <span className="font-semibold">{label}</span>
      <code className="break-all rounded bg-[#f6f8fa] px-2 py-1 text-sm">{value}</code>
      <button className="w-fit rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={onCopy}>
        Copy
      </button>
    </div>
  );
}

// apps/qwik-web/src/components/settings/OAuthApplicationsPanel.tsx
import {
  $,
  type PropFunction,
  component$,
  isBrowser,
  useSignal,
  useTask$,
} from "@builder.io/qwik";
import { Drawer } from "~/components/ui/Drawer";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type OAuthApplication = {
  id: string;
  client_id: string;
  name: string;
  redirect_uri: string;
  scopes: string[];
  created_at: string;
  updated_at: string;
};

type CreatedOAuthApplication = {
  application: OAuthApplication;
  client_secret: string;
};

export const OAuthApplicationsPanel = component$(() => {
  const applications = useSignal<OAuthApplication[]>([]);
  const activeApplication = useSignal<OAuthApplication | null>(null);
  const isCreateOpen = useSignal(false);
  const message = useSignal("");
  const revealedSecret = useSignal<string | null>(null);

  const loadApplications = $(async () => {
    const token = getAuthToken();
    if (!token) {
      applications.value = [];
      message.value = "Sign in to manage OAuth applications.";
      return;
    }

    const response = await fetch(`${publicApiBaseUrl()}/oauth/applications`, {
      headers: { authorization: `Bearer ${token}` },
    });
    if (!response.ok) {
      message.value = `Failed to load OAuth applications: ${response.status}`;
      return;
    }

    const body = (await response.json()) as { data: OAuthApplication[] };
    applications.value = body.data;
    message.value = "";
  });

  useTask$(async () => {
    if (!isBrowser || !getAuthToken()) {
      return;
    }
    await loadApplications();
  });

  const createApplication = $(async (
    _event: SubmitEvent,
    formElement: HTMLFormElement,
  ) => {
    const token = getAuthToken();
    if (!token) {
      message.value = "Sign in to create OAuth applications.";
      return;
    }

    const form = new FormData(formElement);
    const scopes = String(form.get("scopes") ?? "api read_user read_repository")
      .split(/\s+/)
      .map((scope) => scope.trim())
      .filter(Boolean);

    const response = await fetch(`${publicApiBaseUrl()}/oauth/applications`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        name: form.get("name"),
        redirect_uri: form.get("redirectUri"),
        scopes,
      }),
    });
    if (!response.ok) {
      message.value = `Failed to create OAuth application: ${response.status}`;
      return;
    }

    const body = (await response.json()) as CreatedOAuthApplication;
    revealedSecret.value = body.client_secret;
    activeApplication.value = body.application;
    message.value =
      "OAuth application created. Copy the secret now; it will not be shown again.";
    formElement.reset();
    isCreateOpen.value = false;
    await loadApplications();
  });

  const rotateSecret = $(async (application: OAuthApplication) => {
    const token = getAuthToken();
    if (!token) {
      message.value = "Sign in to rotate application secrets.";
      return;
    }

    const response = await fetch(
      `${publicApiBaseUrl()}/oauth/applications/${application.id}/rotate-secret`,
      {
        method: "POST",
        headers: { authorization: `Bearer ${token}` },
      },
    );
    if (!response.ok) {
      message.value = `Failed to rotate secret: ${response.status}`;
      return;
    }

    const body = (await response.json()) as CreatedOAuthApplication;
    revealedSecret.value = body.client_secret;
    activeApplication.value = body.application;
    message.value = "Client secret rotated. Copy the new secret now.";
    await loadApplications();
  });

  const deleteApplication = $(async (application: OAuthApplication) => {
    const token = getAuthToken();
    if (!token) {
      message.value = "Sign in to delete OAuth applications.";
      return;
    }

    const response = await fetch(
      `${publicApiBaseUrl()}/oauth/applications/${application.id}`,
      {
        method: "DELETE",
        headers: { authorization: `Bearer ${token}` },
      },
    );
    if (!response.ok) {
      message.value = `Failed to delete application: ${response.status}`;
      return;
    }

    activeApplication.value = null;
    revealedSecret.value = null;
    message.value = "OAuth application deleted and its tokens revoked.";
    await loadApplications();
  });

  const copy = $(async (value: string) => {
    await navigator.clipboard.writeText(value);
    message.value = "Copied to clipboard.";
  });

  return (
    <section class="settings-resource-panel">
      <div class="settings-resource-panel__header">
        <strong>OAuth applications</strong>
        <div class="settings-resource-panel__actions">
          <button
            class="settings-resource-panel__secondary-button"
            type="button"
            onClick$={loadApplications}
          >
            Refresh
          </button>
          <button
            class="settings-resource-panel__primary-button"
            type="button"
            onClick$={() => {
              isCreateOpen.value = true;
            }}
          >
            New application
          </button>
        </div>
      </div>
      {message.value ? (
        <div class="settings-resource-panel__message">{message.value}</div>
      ) : null}
      <div class="settings-resource-panel__body">
        {applications.value.length === 0 ? (
          <div class="settings-resource-panel__empty">
            No OAuth applications yet.
          </div>
        ) : (
          applications.value.map((application) => (
            <article class="settings-resource-item" key={application.id}>
              <div class="oauth-panel__application-header">
                <div>
                  <strong>{application.name}</strong>
                  <p class="oauth-panel__subtle">{application.redirect_uri}</p>
                </div>
                <button
                  class="settings-resource-panel__secondary-button"
                  type="button"
                  onClick$={() => {
                    activeApplication.value = application;
                  }}
                >
                  Manage
                </button>
              </div>
              <span class="oauth-panel__subtle">
                Scopes: {application.scopes.join(", ")}
              </span>
            </article>
          ))
        )}
      </div>

      <Drawer
        isOpen={isCreateOpen.value}
        onClose$={$(() => {
          isCreateOpen.value = false;
        })}
        title="New OAuth application"
      >
        <form
          class="settings-drawer-form"
          onSubmit$={createApplication}
          preventdefault:submit
        >
          <label class="settings-drawer-form__label">
            Name
            <input
              class="settings-drawer-form__input"
              name="name"
              placeholder="Dokploy"
              required
            />
          </label>
          <label class="settings-drawer-form__label">
            Redirect URI
            <input
              class="settings-drawer-form__input"
              name="redirectUri"
              placeholder="https://your-dokploy-domain.com/api/providers/gitlab/callback"
              required
            />
          </label>
          <label class="settings-drawer-form__label">
            Scopes
            <input
              class="settings-drawer-form__input"
              name="scopes"
              value="api read_user read_repository"
            />
          </label>
          <button class="settings-resource-panel__primary-button" type="submit">
            Create application
          </button>
        </form>
      </Drawer>

      <Drawer
        isOpen={activeApplication.value !== null}
        onClose$={$(() => {
          activeApplication.value = null;
        })}
        title={activeApplication.value?.name ?? "OAuth application"}
      >
        {activeApplication.value ? (
          <div class="oauth-panel__details">
            <InfoRow
              label="Application ID"
              value={activeApplication.value.client_id}
              onCopy$={() => copy(activeApplication.value!.client_id)}
            />
            <InfoRow
              label="Redirect URI"
              value={activeApplication.value.redirect_uri}
              onCopy$={() => copy(activeApplication.value!.redirect_uri)}
            />
            {revealedSecret.value ? (
              <InfoRow
                label="Application Secret"
                value={revealedSecret.value}
                onCopy$={() => copy(revealedSecret.value!)}
              />
            ) : null}
            <div class="oauth-panel__hint">
              <p class="oauth-panel__hint-title">Dokploy setup</p>
              <p class="oauth-panel__subtle">
                Use this Diggit server as Dokploy&apos;s Gitlab URL, then paste
                the Application ID and Secret above.
              </p>
            </div>
            <div class="oauth-panel__actions">
              <button
                class="settings-resource-panel__secondary-button"
                type="button"
                onClick$={() => rotateSecret(activeApplication.value!)}
              >
                Rotate secret
              </button>
              <button
                class="oauth-panel__danger-button"
                type="button"
                onClick$={() => deleteApplication(activeApplication.value!)}
              >
                Delete application
              </button>
            </div>
          </div>
        ) : null}
      </Drawer>
    </section>
  );
});

type InfoRowProps = {
  label: string;
  onCopy$: PropFunction<() => void>;
  value: string;
};

const InfoRow = component$(({ label, onCopy$, value }: InfoRowProps) => {
  return (
    <div class="oauth-panel__info-row">
      <span class="oauth-panel__info-label">{label}</span>
      <code class="oauth-panel__info-value">{value}</code>
      <button
        class="settings-resource-panel__secondary-button"
        type="button"
        onClick$={onCopy$}
      >
        Copy
      </button>
    </div>
  );
});
