// apps/web/src/components/OAuthTokensPanel.tsx
"use client";

import { authHeaders, getAuthToken } from "@/lib/auth-session";
import { apiBaseUrl } from "@/lib/runtime-config";
import { useEffect, useState } from "react";

const API_URL = apiBaseUrl();

export type OAuthToken = {
  id: string;
  application_id: string;
  application_name: string;
  scopes: string[];
  expires_at: string;
  revoked_at: string | null;
  last_used_at: string | null;
  created_at: string;
};

export function OAuthTokensPanel({ initialTokens = [] }: { initialTokens?: OAuthToken[] }) {
  const [tokens, setTokens] = useState<OAuthToken[]>(initialTokens);
  const [message, setMessage] = useState("");

  async function loadTokens() {
    const response = await fetch(`${API_URL}/oauth/tokens`, { headers: authHeaders() });
    if (!response.ok) {
      setMessage(`Failed to load OAuth tokens: ${response.status}`);
      return;
    }
    const body = (await response.json()) as { data: OAuthToken[] };
    setTokens(body.data);
  }

  useEffect(() => {
    if (initialTokens.length > 0 || !getAuthToken()) {
      return;
    }
    void loadTokens();
  }, [initialTokens.length]);

  async function revokeToken(token: OAuthToken) {
    const response = await fetch(`${API_URL}/oauth/tokens/${token.id}`, {
      method: "DELETE",
      headers: authHeaders(),
    });
    if (!response.ok) {
      setMessage(`Failed to revoke token: ${response.status}`);
      return;
    }
    setMessage(`Revoked ${token.application_name}.`);
    await loadTokens();
  }

  return (
    <section className="rounded-md border border-[#d0d7de] bg-white">
      <div className="flex flex-wrap items-center justify-between gap-2 rounded-t-md border-b border-[#d0d7de] bg-[#f6f8fa] px-4 py-3">
        <strong>Authorized OAuth tokens</strong>
        <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={() => void loadTokens()}>
          Refresh
        </button>
      </div>
      {message ? <div className="border-b border-[#d8dee4] px-4 py-2 text-[#59636e]">{message}</div> : null}
      <div className="grid">
        {tokens.length === 0 ? (
          <div className="p-4 text-[#59636e]">No OAuth tokens yet.</div>
        ) : (
          tokens.map((token) => (
            <article className="grid gap-2 border-b border-[#d8dee4] p-4 last:border-b-0" key={token.id}>
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <strong>{token.application_name}</strong>
                  <p className="text-sm text-[#59636e]">Scopes: {token.scopes.join(", ")}</p>
                </div>
                <button
                  className="rounded-md border border-[#cf222e] bg-white px-3 py-1.5 font-semibold text-[#cf222e] disabled:opacity-50"
                  disabled={token.revoked_at !== null}
                  type="button"
                  onClick={() => void revokeToken(token)}
                >
                  {token.revoked_at ? "Revoked" : "Revoke"}
                </button>
              </div>
              <div className="grid gap-1 text-sm text-[#59636e] sm:grid-cols-3">
                <span>Created: {new Date(token.created_at).toLocaleString()}</span>
                <span>Expires: {new Date(token.expires_at).toLocaleString()}</span>
                <span>Last used: {token.last_used_at ? new Date(token.last_used_at).toLocaleString() : "Never"}</span>
              </div>
            </article>
          ))
        )}
      </div>
    </section>
  );
}

// apps/qwik-web/src/components/settings/OAuthTokensPanel.tsx
import { $, component$, isBrowser, useSignal, useTask$ } from "@builder.io/qwik";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type OAuthToken = {
  id: string;
  application_id: string;
  application_name: string;
  scopes: string[];
  expires_at: string;
  revoked_at: string | null;
  last_used_at: string | null;
  created_at: string;
};

export const OAuthTokensPanel = component$(() => {
  const tokens = useSignal<OAuthToken[]>([]);
  const message = useSignal("");

  const loadTokens = $(async () => {
    const token = getAuthToken();
    if (!token) {
      tokens.value = [];
      message.value = "Sign in to review OAuth tokens.";
      return;
    }

    const response = await fetch(`${publicApiBaseUrl()}/oauth/tokens`, {
      headers: { authorization: `Bearer ${token}` },
    });
    if (!response.ok) {
      message.value = `Failed to load OAuth tokens: ${response.status}`;
      return;
    }

    const body = (await response.json()) as { data: OAuthToken[] };
    tokens.value = body.data;
    message.value = "";
  });

  useTask$(async () => {
    if (!isBrowser || !getAuthToken()) {
      return;
    }
    await loadTokens();
  });

  const revokeToken = $(async (tokenRecord: OAuthToken) => {
    const token = getAuthToken();
    if (!token) {
      message.value = "Sign in to revoke OAuth tokens.";
      return;
    }

    const response = await fetch(
      `${publicApiBaseUrl()}/oauth/tokens/${tokenRecord.id}`,
      {
        method: "DELETE",
        headers: { authorization: `Bearer ${token}` },
      },
    );
    if (!response.ok) {
      message.value = `Failed to revoke token: ${response.status}`;
      return;
    }

    message.value = `Revoked ${tokenRecord.application_name}.`;
    await loadTokens();
  });

  return (
    <section class="settings-resource-panel">
      <div class="settings-resource-panel__header">
        <strong>Authorized OAuth tokens</strong>
        <button
          class="settings-resource-panel__secondary-button"
          type="button"
          onClick$={loadTokens}
        >
          Refresh
        </button>
      </div>
      {message.value ? (
        <div class="settings-resource-panel__message">{message.value}</div>
      ) : null}
      <div class="settings-resource-panel__body">
        {tokens.value.length === 0 ? (
          <div class="settings-resource-panel__empty">No OAuth tokens yet.</div>
        ) : (
          tokens.value.map((tokenRecord) => (
            <article class="settings-resource-item" key={tokenRecord.id}>
              <div class="oauth-panel__application-header">
                <div>
                  <strong>{tokenRecord.application_name}</strong>
                  <p class="oauth-panel__subtle">
                    Scopes: {tokenRecord.scopes.join(", ")}
                  </p>
                </div>
                <button
                  class="oauth-panel__danger-button"
                  disabled={tokenRecord.revoked_at !== null}
                  type="button"
                  onClick$={() => revokeToken(tokenRecord)}
                >
                  {tokenRecord.revoked_at ? "Revoked" : "Revoke"}
                </button>
              </div>
              <div class="oauth-token__grid">
                <span>Created: {formatDateTime(tokenRecord.created_at)}</span>
                <span>Expires: {formatDateTime(tokenRecord.expires_at)}</span>
                <span>
                  Last used:{" "}
                  {tokenRecord.last_used_at
                    ? formatDateTime(tokenRecord.last_used_at)
                    : "Never"}
                </span>
              </div>
            </article>
          ))
        )}
      </div>
    </section>
  );
});

function formatDateTime(value: string) {
  return new Date(value).toLocaleString();
}
