// apps/web/src/components/OrganizationGeneralSettingsForm.tsx
"use client";

import { Drawer } from "@/components/Drawer";
import { authHeaders } from "@/lib/auth-session";
import { apiBaseUrl } from "@/lib/runtime-config";
import type { Organization } from "@/lib/api";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

const API_URL = apiBaseUrl();

type OrganizationGeneralSettingsFormProps = {
  organization: Organization;
};

export function OrganizationGeneralSettingsForm({ organization }: OrganizationGeneralSettingsFormProps) {
  const router = useRouter();
  const [displayName, setDisplayName] = useState(organization.display_name);
  const [description, setDescription] = useState(organization.description);
  const [isSaving, setIsSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");

  async function saveOrganization(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsSaving(true);
    setMessage("");

    const response = await fetch(`${API_URL}/organizations/${encodeURIComponent(organization.name)}`, {
      method: "PATCH",
      headers: {
        "content-type": "application/json",
        ...authHeaders(),
      },
      body: JSON.stringify({
        display_name: displayName,
        description,
      }),
    });

    setIsSaving(false);
    if (!response.ok) {
      await showError(response, "Unable to save organization settings.");
      return;
    }

    setMessage("Organization settings saved.");
    router.refresh();
  }

  async function deleteOrganization() {
    if (confirmation !== organization.name) {
      setMessage(`Type ${organization.name} to confirm deletion.`);
      return;
    }

    setIsSaving(true);
    setMessage("");
    const response = await fetch(`${API_URL}/organizations/${encodeURIComponent(organization.name)}`, {
      method: "DELETE",
      headers: authHeaders(),
    });
    setIsSaving(false);

    if (!response.ok) {
      await showError(response, "Unable to delete organization.");
      return;
    }

    router.push("/organizations");
    router.refresh();
  }

  async function showError(response: Response, fallback: string) {
    const body = (await response.json().catch(() => null)) as { error?: string } | null;
    setMessage(body?.error ?? `${fallback} (${response.status})`);
  }

  return (
    <main className="grid gap-6">
      <section className="grid gap-2">
        <h2 className="text-2xl font-semibold tracking-tight">General settings</h2>
        <p className="text-[#59636e]">Control organization identity and administrative actions.</p>
      </section>

      <form className="grid gap-6" onSubmit={saveOrganization}>
        <section className="grid gap-4 rounded-md border border-[#d0d7de] bg-white p-5">
          <div>
            <h3 className="text-lg font-semibold">Organization profile</h3>
            <p className="text-sm text-[#59636e]">Update the public name and description for @{organization.name}.</p>
          </div>
          <label className="grid gap-2">
            <span className="font-semibold">Display name</span>
            <input
              className="max-w-md rounded-md border border-[#d0d7de] bg-white px-3 py-2"
              required
              value={displayName}
              onChange={(event) => setDisplayName(event.target.value)}
            />
          </label>
          <label className="grid gap-2">
            <span className="font-semibold">Description</span>
            <textarea
              className="min-h-28 rounded-md border border-[#d0d7de] bg-white px-3 py-2"
              value={description}
              onChange={(event) => setDescription(event.target.value)}
            />
          </label>
          <div className="flex items-center gap-3">
            <button className="rounded-md border border-black/15 bg-[#1a7f37] px-4 py-2 font-bold text-white disabled:opacity-60" disabled={isSaving} type="submit">
              {isSaving ? "Saving..." : "Save changes"}
            </button>
            {message ? <p className="text-sm text-[#59636e]">{message}</p> : null}
          </div>
        </section>
      </form>

      <section className="rounded-md border border-[#cf222e] bg-white">
        <div className="border-b border-[#d8dee4] p-5">
          <h3 className="text-xl font-semibold text-[#cf222e]">Danger Zone</h3>
        </div>
        <div className="flex flex-wrap items-center justify-between gap-4 p-5">
          <div>
            <h4 className="font-semibold">Delete this organization</h4>
            <p className="text-sm text-[#59636e]">Permanently delete this organization. Repositories must be moved or deleted first.</p>
          </div>
          <button className="rounded-md border border-[#cf222e] bg-white px-3 py-1.5 font-semibold text-[#cf222e] hover:bg-[#fff8f8]" type="button" onClick={() => setIsDeleteOpen(true)}>
            Delete this organization
          </button>
        </div>
      </section>

      <Drawer isOpen={isDeleteOpen} title="Delete organization" onClose={() => setIsDeleteOpen(false)}>
        <div className="grid gap-4">
          <p className="text-[#59636e]">Type {organization.name} to confirm deletion.</p>
          <input
            className="max-w-sm rounded-md border border-[#d0d7de] bg-white px-3 py-2"
            placeholder={organization.name}
            value={confirmation}
            onChange={(event) => setConfirmation(event.target.value)}
          />
          <button
            className="w-fit rounded-md border border-[#cf222e] bg-white px-3 py-1.5 font-semibold text-[#cf222e] hover:bg-[#fff8f8] disabled:opacity-60"
            disabled={isSaving}
            type="button"
            onClick={deleteOrganization}
          >
            {isSaving ? "Deleting..." : "Delete organization"}
          </button>
        </div>
      </Drawer>
    </main>
  );
}

// apps/qwik-web/src/components/settings/OrganizationGeneralSettingsForm.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { useNavigate } from "@builder.io/qwik-city";
import { Drawer } from "~/components/ui/Drawer";
import type { Organization } from "~/lib/api";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type OrganizationGeneralSettingsFormProps = {
  organization: Organization;
};

export const OrganizationGeneralSettingsForm = component$(
  ({ organization }: OrganizationGeneralSettingsFormProps) => {
    const nav = useNavigate();
    const displayName = useSignal(organization.display_name);
    const description = useSignal(organization.description);
    const isSaving = useSignal(false);
    const message = useSignal("");
    const isDeleteOpen = useSignal(false);
    const confirmation = useSignal("");

    const saveOrganization = $(async () => {
      const token = getAuthToken();
      if (!token) {
        message.value = "Sign in to update organization settings.";
        return;
      }

      isSaving.value = true;
      message.value = "";

      const response = await fetch(
        `${publicApiBaseUrl()}/organizations/${encodeURIComponent(organization.name)}`,
        {
          method: "PATCH",
          headers: {
            "content-type": "application/json",
            authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            display_name: displayName.value,
            description: description.value,
          }),
        },
      );

      isSaving.value = false;
      if (!response.ok) {
        await showError(response, message, "Unable to save organization settings.");
        return;
      }

      message.value = "Organization settings saved.";
    });

    const deleteOrganization = $(async () => {
      if (confirmation.value !== organization.name) {
        message.value = `Type ${organization.name} to confirm deletion.`;
        return;
      }

      const token = getAuthToken();
      if (!token) {
        message.value = "Sign in to delete organizations.";
        return;
      }

      isSaving.value = true;
      message.value = "";
      const response = await fetch(
        `${publicApiBaseUrl()}/organizations/${encodeURIComponent(organization.name)}`,
        {
          method: "DELETE",
          headers: { authorization: `Bearer ${token}` },
        },
      );
      isSaving.value = false;

      if (!response.ok) {
        await showError(response, message, "Unable to delete organization.");
        return;
      }

      await nav("/organizations");
    });

    return (
      <main class="settings-general-page">
        <section class="settings-group-page__copy">
          <h2 class="settings-group-page__title">General settings</h2>
          <p class="settings-group-page__description">
            Control organization identity and administrative actions.
          </p>
        </section>

        <section class="settings-general-card">
          <div>
            <h3 class="settings-general-card__title">Organization profile</h3>
            <p class="settings-general-card__description">
              Update the public name and description for @{organization.name}.
            </p>
          </div>
          <label class="settings-drawer-form__label">
            <span class="settings-drawer-form__heading">Display name</span>
            <input
              class="settings-drawer-form__input"
              required
              value={displayName.value}
              onInput$={(event) => {
                displayName.value = (event.target as HTMLInputElement).value;
              }}
            />
          </label>
          <label class="settings-drawer-form__label">
            <span class="settings-drawer-form__heading">Description</span>
            <textarea
              class="settings-drawer-form__textarea settings-drawer-form__textarea--plain"
              value={description.value}
              onInput$={(event) => {
                description.value = (event.target as HTMLTextAreaElement).value;
              }}
            />
          </label>
          <div class="settings-group-page__actions">
            <button
              class="settings-resource-panel__primary-button"
              disabled={isSaving.value}
              type="button"
              onClick$={saveOrganization}
            >
              {isSaving.value ? "Saving..." : "Save changes"}
            </button>
            {message.value ? (
              <p class="settings-group-page__message">{message.value}</p>
            ) : null}
          </div>
        </section>

        <section class="settings-danger-zone">
          <div class="settings-danger-zone__header">
            <h3 class="settings-danger-zone__title">Danger Zone</h3>
          </div>
          <div class="settings-danger-zone__row">
            <div>
              <h4 class="settings-danger-zone__row-title">Delete this organization</h4>
              <p class="settings-danger-zone__row-description">
                Permanently delete this organization. Repositories must be moved
                or deleted first.
              </p>
            </div>
            <button
              class="oauth-panel__danger-button"
              type="button"
              onClick$={$(() => {
                isDeleteOpen.value = true;
              })}
            >
              Delete this organization
            </button>
          </div>
        </section>

        <Drawer
          isOpen={isDeleteOpen.value}
          onClose$={$(() => {
            isDeleteOpen.value = false;
          })}
          title="Delete organization"
        >
          <div class="settings-drawer-form">
            <p class="settings-group-page__message">
              Type {organization.name} to confirm deletion.
            </p>
            <input
              class="settings-drawer-form__input"
              placeholder={organization.name}
              value={confirmation.value}
              onInput$={(event) => {
                confirmation.value = (event.target as HTMLInputElement).value;
              }}
            />
            <button
              class="oauth-panel__danger-button"
              disabled={isSaving.value}
              type="button"
              onClick$={deleteOrganization}
            >
              {isSaving.value ? "Deleting..." : "Delete organization"}
            </button>
          </div>
        </Drawer>
      </main>
    );
  },
);

async function showError(
  response: Response,
  message: { value: string },
  fallback: string,
) {
  const body = (await response.json().catch(() => null)) as { error?: string } | null;
  message.value = body?.error ?? `${fallback} (${response.status})`;
}
