// apps/web/src/components/SecretsVariablesPanel.tsx
"use client";

import { Drawer } from "@/components/Drawer";
import { authHeaders, getAuthToken } from "@/lib/auth-session";
import type { RunnerSecret, RunnerVariable } from "@/lib/api";
import { apiBaseUrl } from "@/lib/runtime-config";
import { FormEvent, useEffect, useState } from "react";

const API_URL = apiBaseUrl();

type SecretsVariablesPanelProps = {
  scopeLabel: "repository" | "organization";
  secrets: RunnerSecret[];
  variables: RunnerVariable[];
  secretsPath: string;
  variablesPath: string;
};

type DrawerMode = "secret" | "variable" | null;

export function SecretsVariablesPanel({ scopeLabel, secrets, secretsPath, variables, variablesPath }: SecretsVariablesPanelProps) {
  const [secretsState, setSecretsState] = useState(secrets);
  const [variablesState, setVariablesState] = useState(variables);
  const [mode, setMode] = useState<DrawerMode>(null);
  const [name, setName] = useState("");
  const [value, setValue] = useState("");
  const [environment, setEnvironment] = useState("");
  const [message, setMessage] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  const scopeTitle = scopeLabel[0].toUpperCase() + scopeLabel.slice(1);
  const environmentSecrets = secretsState.filter((secret) => secret.environment);
  const scopedSecrets = secretsState.filter((secret) => !secret.environment);
  const environmentVariables = variablesState.filter((variable) => variable.environment);
  const scopedVariables = variablesState.filter((variable) => !variable.environment);

  async function loadConfigs() {
    const [secretsResponse, variablesResponse] = await Promise.all([
      fetch(`${API_URL}${secretsPath}`, { headers: authHeaders() }),
      fetch(`${API_URL}${variablesPath}`, { headers: authHeaders() }),
    ]);

    if (!secretsResponse.ok || !variablesResponse.ok) {
      const status = !secretsResponse.ok ? secretsResponse.status : variablesResponse.status;
      setMessage(`Failed to load ${scopeLabel} configuration. (${status})`);
      return;
    }

    const [nextSecrets, nextVariables] = (await Promise.all([
      secretsResponse.json(),
      variablesResponse.json(),
    ])) as [{ data: RunnerSecret[] }, { data: RunnerVariable[] }];

    setSecretsState(nextSecrets.data);
    setVariablesState(nextVariables.data);
  }

  useEffect(() => {
    if ((secrets.length > 0 || variables.length > 0) || !getAuthToken()) {
      return;
    }
    void loadConfigs();
  }, [secrets.length, variables.length]);

  async function submitConfig(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const path = mode === "secret" ? secretsPath : variablesPath;
    setIsSaving(true);
    setMessage("");

    const response = await fetch(`${API_URL}${path}`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        ...authHeaders(),
      },
      body: JSON.stringify({
        name,
        value,
        environment: environment || null,
      }),
    });

    setIsSaving(false);
    if (!response.ok) {
      const body = (await response.json().catch(() => null)) as { error?: string } | null;
      setMessage(body?.error ?? `Failed to save ${mode}.`);
      return;
    }

    setName("");
    setValue("");
    setEnvironment("");
    setMode(null);
    await loadConfigs();
  }

  return (
    <main className="grid gap-6">
      <section className="grid gap-2">
        <h2 className="text-2xl font-semibold tracking-tight">Secrets and variables</h2>
        <p className="text-[#59636e]">Configure runner secrets and environment variables for this {scopeLabel}.</p>
      </section>

      <section className="rounded-md border border-[#d0d7de] bg-white">
        <Header title="Environment secrets" action="New secret" onClick={() => setMode("secret")} />
        <ConfigList emptyText="This environment has no secrets." items={environmentSecrets} />
      </section>

      <section className="rounded-md border border-[#d0d7de] bg-white">
        <Header title={`${scopeTitle} secrets`} action="New secret" onClick={() => setMode("secret")} />
        <ConfigList emptyText={`This ${scopeLabel} has no secrets.`} items={scopedSecrets} />
      </section>

      <section className="rounded-md border border-[#d0d7de] bg-white">
        <Header title="Environment variables" action="New variable" onClick={() => setMode("variable")} />
        <ConfigList emptyText="This environment has no variables." items={environmentVariables} showValue />
      </section>

      <section className="rounded-md border border-[#d0d7de] bg-white">
        <Header title={`${scopeTitle} variables`} action="New variable" onClick={() => setMode("variable")} />
        <ConfigList emptyText={`This ${scopeLabel} has no variables.`} items={scopedVariables} showValue />
      </section>

      <Drawer isOpen={mode !== null} title={mode === "secret" ? "New secret" : "New variable"} onClose={() => setMode(null)}>
        <form className="grid gap-4" onSubmit={submitConfig}>
          <label className="grid gap-2">
            <span className="font-semibold">Name</span>
            <input
              className="max-w-md rounded-md border border-[#d0d7de] bg-white px-3 py-2"
              placeholder="DEPLOY_TOKEN"
              required
              value={name}
              onChange={(event) => setName(event.target.value)}
            />
          </label>
          <label className="grid gap-2">
            <span className="font-semibold">Value</span>
            <textarea
              className="min-h-28 rounded-md border border-[#d0d7de] bg-white px-3 py-2"
              required
              value={value}
              onChange={(event) => setValue(event.target.value)}
            />
          </label>
          <label className="grid gap-2">
            <span className="font-semibold">Environment</span>
            <input
              className="max-w-md rounded-md border border-[#d0d7de] bg-white px-3 py-2"
              placeholder="Optional, for example production"
              value={environment}
              onChange={(event) => setEnvironment(event.target.value)}
            />
          </label>
          <div className="flex items-center gap-3">
            <button className="w-fit rounded-md border border-black/15 bg-[#1a7f37] px-4 py-2 font-bold text-white disabled:opacity-60" disabled={isSaving} type="submit">
              {isSaving ? "Saving..." : "Save"}
            </button>
            {message ? <p className="text-sm text-[#59636e]">{message}</p> : null}
          </div>
        </form>
      </Drawer>
    </main>
  );
}

function Header({ action, onClick, title }: { action: string; onClick: () => void; title: string }) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#d8dee4] bg-[#f6f8fa] px-5 py-3">
      <h3 className="font-semibold">{title}</h3>
      <button className="rounded-md border border-[#d0d7de] bg-white px-3 py-1.5 font-semibold" type="button" onClick={onClick}>
        {action}
      </button>
    </div>
  );
}

function ConfigList({ emptyText, items, showValue = false }: { emptyText: string; items: Array<RunnerSecret | RunnerVariable>; showValue?: boolean }) {
  if (items.length === 0) {
    return <p className="p-5 text-[#59636e]">{emptyText}</p>;
  }

  return (
    <div className="grid">
      {items.map((item) => (
        <article className="flex flex-wrap items-center justify-between gap-3 border-b border-[#d8dee4] p-5 last:border-b-0" key={item.id}>
          <div>
            <h4 className="font-mono font-semibold">{item.name}</h4>
            <p className="text-sm text-[#59636e]">{item.environment ? `Environment: ${item.environment}` : "No environment"}</p>
          </div>
          {showValue && "value" in item ? <span className="max-w-md truncate font-mono text-sm text-[#59636e]">{item.value}</span> : null}
        </article>
      ))}
    </div>
  );
}

// apps/qwik-web/src/components/settings/SecretsVariablesPanel.tsx
import {
  $,
  type PropFunction,
  component$,
  isBrowser,
  useSignal,
  useTask$,
} from "@builder.io/qwik";
import { Drawer } from "~/components/ui/Drawer";
import type { RunnerSecret, RunnerVariable } from "~/lib/api";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl } from "~/lib/api";

type SecretsVariablesPanelProps = {
  scopeLabel: "organization" | "repository";
  secrets: RunnerSecret[];
  secretsPath: string;
  variables: RunnerVariable[];
  variablesPath: string;
};

type DrawerMode = "secret" | "variable" | null;

export const SecretsVariablesPanel = component$(
  ({
    scopeLabel,
    secrets,
    secretsPath,
    variables,
    variablesPath,
  }: SecretsVariablesPanelProps) => {
    const secretsState = useSignal(secrets);
    const variablesState = useSignal(variables);
    const mode = useSignal<DrawerMode>(null);
    const name = useSignal("");
    const value = useSignal("");
    const environment = useSignal("");
    const message = useSignal("");
    const isSaving = useSignal(false);

    const scopeTitle = `${scopeLabel[0].toUpperCase()}${scopeLabel.slice(1)}`;
    const environmentSecrets = secretsState.value.filter((secret) => secret.environment);
    const scopedSecrets = secretsState.value.filter((secret) => !secret.environment);
    const environmentVariables = variablesState.value.filter(
      (variable) => variable.environment,
    );
    const scopedVariables = variablesState.value.filter((variable) => !variable.environment);

    const loadConfigs = $(async () => {
      const token = getAuthToken();
      if (!token) {
        message.value = `Sign in to manage ${scopeLabel} secrets and variables.`;
        return;
      }

      const [secretsResponse, variablesResponse] = await Promise.all([
        fetch(`${publicApiBaseUrl()}${secretsPath}`, {
          headers: { authorization: `Bearer ${token}` },
        }),
        fetch(`${publicApiBaseUrl()}${variablesPath}`, {
          headers: { authorization: `Bearer ${token}` },
        }),
      ]);

      if (!secretsResponse.ok || !variablesResponse.ok) {
        const status = !secretsResponse.ok
          ? secretsResponse.status
          : variablesResponse.status;
        message.value = `Failed to load ${scopeLabel} configuration. (${status})`;
        return;
      }

      const [nextSecrets, nextVariables] = (await Promise.all([
        secretsResponse.json(),
        variablesResponse.json(),
      ])) as [{ data: RunnerSecret[] }, { data: RunnerVariable[] }];

      secretsState.value = nextSecrets.data;
      variablesState.value = nextVariables.data;
      message.value = "";
    });

    useTask$(async () => {
      if (!isBrowser) {
        return;
      }
      if (secrets.length > 0 || variables.length > 0) {
        return;
      }
      await loadConfigs();
    });

    const submitConfig = $(async () => {
      const token = getAuthToken();
      if (!token || !mode.value) {
        message.value = `Sign in to manage ${scopeLabel} secrets and variables.`;
        return;
      }

      const path = mode.value === "secret" ? secretsPath : variablesPath;
      isSaving.value = true;
      message.value = "";

      const response = await fetch(`${publicApiBaseUrl()}${path}`, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          name: name.value,
          value: value.value,
          environment: environment.value || null,
        }),
      });

      isSaving.value = false;
      if (!response.ok) {
        const body = (await response.json().catch(() => null)) as
          | { error?: string }
          | null;
        message.value = body?.error ?? `Failed to save ${mode.value}.`;
        return;
      }

      name.value = "";
      value.value = "";
      environment.value = "";
      mode.value = null;
      await loadConfigs();
    });

    return (
      <main class="settings-group-page">
        <section class="settings-group-page__copy">
          <h2 class="settings-group-page__title">Secrets and variables</h2>
          <p class="settings-group-page__description">
            Configure runner secrets and environment variables for this{" "}
            {scopeLabel}.
          </p>
        </section>

        <section class="settings-resource-panel">
          <Header
            action="New secret"
            onClick$={$(() => {
              mode.value = "secret";
            })}
            title="Environment secrets"
          />
          <ConfigList
            emptyText="This environment has no secrets."
            items={environmentSecrets}
          />
        </section>

        <section class="settings-resource-panel">
          <Header
            action="New secret"
            onClick$={$(() => {
              mode.value = "secret";
            })}
            title={`${scopeTitle} secrets`}
          />
          <ConfigList
            emptyText={`This ${scopeLabel} has no secrets.`}
            items={scopedSecrets}
          />
        </section>

        <section class="settings-resource-panel">
          <Header
            action="New variable"
            onClick$={$(() => {
              mode.value = "variable";
            })}
            title="Environment variables"
          />
          <ConfigList
            emptyText="This environment has no variables."
            items={environmentVariables}
            showValue
          />
        </section>

        <section class="settings-resource-panel">
          <Header
            action="New variable"
            onClick$={$(() => {
              mode.value = "variable";
            })}
            title={`${scopeTitle} variables`}
          />
          <ConfigList
            emptyText={`This ${scopeLabel} has no variables.`}
            items={scopedVariables}
            showValue
          />
        </section>

        <Drawer
          isOpen={mode.value !== null}
          onClose$={$(() => {
            mode.value = null;
          })}
          title={mode.value === "secret" ? "New secret" : "New variable"}
        >
          <div class="settings-drawer-form">
            <label class="settings-drawer-form__label">
              <span class="settings-drawer-form__heading">Name</span>
              <input
                class="settings-drawer-form__input"
                placeholder="DEPLOY_TOKEN"
                required
                value={name.value}
                onInput$={(event) => {
                  name.value = (event.target as HTMLInputElement).value;
                }}
              />
            </label>
            <label class="settings-drawer-form__label">
              <span class="settings-drawer-form__heading">Value</span>
              <textarea
                class="settings-drawer-form__textarea settings-drawer-form__textarea--plain"
                required
                value={value.value}
                onInput$={(event) => {
                  value.value = (event.target as HTMLTextAreaElement).value;
                }}
              />
            </label>
            <label class="settings-drawer-form__label">
              <span class="settings-drawer-form__heading">Environment</span>
              <input
                class="settings-drawer-form__input"
                placeholder="Optional, for example production"
                value={environment.value}
                onInput$={(event) => {
                  environment.value = (event.target as HTMLInputElement).value;
                }}
              />
            </label>
            <div class="settings-group-page__actions">
              <button
                class="settings-resource-panel__primary-button"
                disabled={isSaving.value}
                type="button"
                onClick$={submitConfig}
              >
                {isSaving.value ? "Saving..." : "Save"}
              </button>
              {message.value ? (
                <p class="settings-group-page__message">{message.value}</p>
              ) : null}
            </div>
          </div>
        </Drawer>
      </main>
    );
  },
);

const Header = component$(
  ({
    action,
    onClick$,
    title,
  }: {
    action: string;
    onClick$: PropFunction<() => void>;
    title: string;
  }) => {
    return (
      <div class="settings-resource-panel__header">
        <h3>{title}</h3>
        <button
          class="settings-resource-panel__secondary-button"
          type="button"
          onClick$={onClick$}
        >
          {action}
        </button>
      </div>
    );
  },
);

const ConfigList = component$(
  ({
    emptyText,
    items,
    showValue = false,
  }: {
    emptyText: string;
    items: Array<RunnerSecret | RunnerVariable>;
    showValue?: boolean;
  }) => {
    if (items.length === 0) {
      return <p class="settings-resource-panel__empty">{emptyText}</p>;
    }

    return (
      <div class="settings-resource-panel__body">
        {items.map((item) => (
          <article class="settings-resource-item settings-config-item" key={item.id}>
            <div>
              <h4 class="settings-config-item__title">{item.name}</h4>
              <p class="settings-config-item__environment">
                {item.environment
                  ? `Environment: ${item.environment}`
                  : "No environment"}
              </p>
            </div>
            {showValue && "value" in item ? (
              <span class="settings-config-item__value">{item.value}</span>
            ) : null}
          </article>
        ))}
      </div>
    );
  },
);
