// apps/web/src/app/organizations/[org]/settings/collaborators/page.tsx
import { CollaboratorsPanel } from "@/components/CollaboratorsPanel";
import { listOrganizationMembers } from "@/lib/api";

type Props = {
  params: Promise<{ org: string }>;
};

export default async function OrganizationCollaboratorsPage({ params }: Props) {
  const { org } = await params;
  const decodedOrg = decodeURIComponent(org);
  const collaborators = await listOrganizationMembers(decodedOrg).catch(() => ({ data: [] }));

  return (
    <CollaboratorsPanel
      addPath={`/organizations/${encodeURIComponent(decodedOrg)}/members`}
      collaborators={collaborators.data}
      permissionName="role"
      scopeLabel="organization"
    />
  );
}

// apps/qwik-web/src/routes/organizations/[org]/settings/collaborators/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { CollaboratorsPanel } from "~/components/settings/CollaboratorsPanel";
import { listOrganizationMembers } from "~/lib/api";

export const useOrganizationCollaboratorsPage = routeLoader$(async ({ params }) => {
  const collaborators = await listOrganizationMembers(params.org).catch(() => ({
    data: [],
  }));

  return {
    collaborators: collaborators.data,
    encodedOrg: encodeURIComponent(params.org),
  };
});

export default component$(() => {
  const route = useOrganizationCollaboratorsPage();

  return (
    <CollaboratorsPanel
      addPath={`/organizations/${route.value.encodedOrg}/members`}
      collaborators={route.value.collaborators}
      permissionName="role"
      scopeLabel="organization"
    />
  );
});
