// apps/qwik-web/src/routes/settings/oauth/applications/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { OAuthApplicationsPanel } from "~/components/settings/OAuthApplicationsPanel";

export default component$(() => {
  return (
    <div class="settings-page">
      <section class="settings-page__hero">
        <p class="settings-page__eyebrow">Account settings</p>
        <h1 class="settings-page__title">OAuth applications</h1>
        <p class="settings-page__description">
          Register Dokploy or other clients that need GitLab-compatible access
          to your Diggit repositories.
        </p>
      </section>
      <OAuthApplicationsPanel />
    </div>
  );
});

export const head: DocumentHead = {
  title: "OAuth Applications · Diggit",
};

// apps/web/src/app/settings/oauth/applications/page.tsx
import { OAuthApplicationsPanel } from "@/components/OAuthApplicationsPanel";

export default function OAuthApplicationsPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          Account settings
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">OAuth applications</h1>
        <p className="text-[#59636e]">
          Register Dokploy or other clients that need GitLab-compatible access to your Diggit repositories.
        </p>
      </section>
      <OAuthApplicationsPanel />
    </div>
  );
}
