// apps/web/src/app/organizations/[org]/settings/runners/page.tsx
import { RunnerPanel } from "@/components/RunnerPanel";

type Props = {
  params: Promise<{ org: string }>;
};

export default async function OrganizationRunnersPage({ params }: Props) {
  const { org } = await params;
  const decodedOrg = decodeURIComponent(org);

  return (
    <main className="grid gap-3.5">
      <section className="mb-6 rounded-md border border-[#d0d7de] bg-white p-5">
        <h2 className="mb-3 text-2xl font-semibold tracking-tight">{decodedOrg} runners</h2>
        <p className="text-[#59636e]">Manage organization-scope Gitea-compatible runners.</p>
      </section>
      <RunnerPanel
        listPath={`/orgs/${encodeURIComponent(decodedOrg)}/actions/runners`}
        scopeLabel={`${decodedOrg} organization`}
        tokenPath={`/orgs/${encodeURIComponent(decodedOrg)}/actions/runners/registration-token`}
      />
    </main>
  );
}

// apps/qwik-web/src/routes/organizations/[org]/settings/runners/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { RunnerPanel } from "~/components/settings/RunnerPanel";

export const useOrganizationRunnersPage = routeLoader$(({ params }) => {
  return {
    encodedOrg: encodeURIComponent(params.org),
    org: params.org,
  };
});

export default component$(() => {
  const route = useOrganizationRunnersPage();

  return (
    <div class="settings-group-page">
      <section class="settings-group-page__copy">
        <h2 class="settings-group-page__title">{route.value.org} runners</h2>
        <p class="settings-group-page__description">
          Manage organization-scope Gitea-compatible runners.
        </p>
      </section>
      <RunnerPanel
        listPath={`/orgs/${route.value.encodedOrg}/actions/runners`}
        scopeLabel={`${route.value.org} organization`}
        tokenPath={`/orgs/${route.value.encodedOrg}/actions/runners/registration-token`}
      />
    </div>
  );
});
