// apps/qwik-web/src/routes/[owner]/[name]/releases/[tag]/edit/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { ReleaseEditPanel } from "~/components/releases/RepositoryReleasesPanel";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import {
  getRelease,
  getRepository,
  listPullRequests,
  listReleases,
} from "~/lib/api";

export const useEditRepositoryReleasePage = routeLoader$(async ({ params }) => {
  const [repo, pullRequests, release, releaseCount] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    getRelease(params.owner, params.name, params.tag),
    listReleases(params.owner, params.name, {
      page: 1,
      limit: 1,
      status: "published",
    }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
  ]);

  return {
    baseHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}`,
    name: params.name,
    owner: params.owner,
    pullRequestsCount: pullRequests.pagination.total,
    release,
    releasesCount: releaseCount.pagination.total,
    repo,
  };
});

export default component$(() => {
  const route = useEditRepositoryReleasePage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="releases"
        pullRequestsCount={route.value.pullRequestsCount}
        releasesCount={route.value.releasesCount}
        repo={route.value.repo}
      />
      <RepoPageContent>
        <ReleaseEditPanel
          baseHref={route.value.baseHref}
          name={route.value.name}
          owner={route.value.owner}
          release={route.value.release}
        />
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Edit Release · Diggit",
};

// apps/web/src/app/[owner]/[name]/releases/[tag]/edit/page.tsx
import { ReleaseEditPanel } from "@/components/RepositoryReleasesPanel";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { getRelease, getRepository, listPullRequests, listReleases } from "@/lib/api";

type Props = {
  params: Promise<{
    owner: string;
    name: string;
    tag: string;
  }>;
};

export default async function EditRepositoryReleasePage({ params }: Props) {
  const { owner, name, tag } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const decodedTag = decodeURIComponent(tag);
  const baseHref = repoHref(decodedOwner, decodedName);
  const [repo, pullRequests, release, releaseCount] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [] })),
    getRelease(decodedOwner, decodedName, decodedTag),
    listReleases(decodedOwner, decodedName, { page: 1, limit: 1, status: "published" }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="releases" pullRequestsCount={pullRequests.data.length} releasesCount={releaseCount.pagination.total} repo={repo} />

      <RepoPageContent>
        <ReleaseEditPanel baseHref={baseHref} name={decodedName} owner={decodedOwner} release={release} />
      </RepoPageContent>
    </div>
  );
}
