// apps/web/src/app/[owner]/[name]/settings/collaborators/page.tsx
import { CollaboratorsPanel } from "@/components/CollaboratorsPanel";
import { listRepositoryCollaborators } from "@/lib/api";

type Props = {
  params: Promise<{ owner: string; name: string }>;
};

export default async function RepositoryCollaboratorsPage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const collaborators = await listRepositoryCollaborators(decodedOwner, decodedName).catch(() => ({ data: [] }));

  return (
    <CollaboratorsPanel
      addPath={`/repos/${encodeURIComponent(decodedOwner)}/${encodeURIComponent(decodedName)}/collaborators`}
      collaborators={collaborators.data}
      permissionName="permission"
      scopeLabel="repository"
    />
  );
}

// apps/qwik-web/src/routes/[owner]/[name]/settings/collaborators/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { CollaboratorsPanel } from "~/components/settings/CollaboratorsPanel";
import { listRepositoryCollaborators } from "~/lib/api";

export const useRepositoryCollaboratorsPage = routeLoader$(async ({ params }) => {
  const collaborators = await listRepositoryCollaborators(
    params.owner,
    params.name,
  ).catch(() => ({ data: [] }));

  return {
    collaborators: collaborators.data,
    encodedName: encodeURIComponent(params.name),
    encodedOwner: encodeURIComponent(params.owner),
  };
});

export default component$(() => {
  const route = useRepositoryCollaboratorsPage();

  return (
    <CollaboratorsPanel
      addPath={`/repos/${route.value.encodedOwner}/${route.value.encodedName}/collaborators`}
      collaborators={route.value.collaborators}
      permissionName="permission"
      scopeLabel="repository"
    />
  );
});
