// apps/qwik-web/src/routes/[owner]/[name]/compare-upstream/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { CommitCompareList } from "~/components/repository/CommitCompareList";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import { SyncForkButton } from "~/components/repository/SyncForkButton";
import { CodeDiff } from "~/components/repository/code/CodeDiff";
import { compareUpstream, getRepository, listPullRequests } from "~/lib/api";

export const useCompareUpstreamPage = routeLoader$(async ({ params }) => {
  const [repo, pullRequests, compare] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    compareUpstream(params.owner, params.name),
  ]);

  return {
    compare,
    name: params.name,
    owner: params.owner,
    pullRequestsCount: pullRequests.pagination.total,
    repo,
  };
});

export default component$(() => {
  const route = useCompareUpstreamPage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="code"
        pullRequestsCount={route.value.pullRequestsCount}
        repo={route.value.repo}
      />
      <RepoPageContent>
        <section class="compare-page__hero">
          <div class="compare-upstream__header">
            <div>
              <h2 class="compare-page__title">Compare with upstream</h2>
              <p class="issue-detail-page__meta">
                {route.value.compare.source ? (
                  <>
                    Original repository:{" "}
                    <a class="compare-upstream__source" href={route.value.compare.source.url}>
                      {route.value.compare.source.owner_handle}/{route.value.compare.source.name}
                    </a>
                  </>
                ) : (
                  "Original repository unavailable."
                )}
              </p>
            </div>
            {route.value.compare.behind_by > 0 ? (
              <SyncForkButton name={route.value.name} owner={route.value.owner} />
            ) : null}
          </div>

          {route.value.compare.status === "unavailable" ? (
            <p class="issue-detail-page__meta">
              {route.value.compare.message ?? "Upstream comparison is unavailable."}
            </p>
          ) : (
            <div class="compare-page__stats">
              <span>{route.value.compare.ahead_by} commits ahead</span>
              <span>{route.value.compare.behind_by} commits behind</span>
              <span class="pull-request-flow__status-pill">
                {route.value.compare.status.replaceAll("_", " ")}
              </span>
            </div>
          )}
        </section>

        <div class="compare-page__lists">
          <CommitCompareList
            commits={route.value.compare.ahead_commits}
            emptyLabel="No commits ahead of upstream."
            title="Ahead commits"
          />
          <CommitCompareList
            commits={route.value.compare.behind_commits}
            emptyLabel="No upstream commits to sync."
            title="Behind commits"
          />
        </div>

        <CodeDiff
          emptyLabel="No diff to show between this fork and upstream."
          files={route.value.compare.files}
        />
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Compare Upstream · Diggit",
};

// apps/web/src/app/[owner]/[name]/compare-upstream/page.tsx
import Link from "next/link";
import { CodeDiff } from "@/components/CodeDiff";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { SyncForkButton } from "@/components/SyncForkButton";
import { compareUpstream, getRepository, listPullRequests, type RepositoryCommit } from "@/lib/api";

type Props = {
  params: Promise<{
    owner: string;
    name: string;
  }>;
};

export default async function CompareUpstreamPage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const baseHref = repoHref(decodedOwner, decodedName);
  const [repo, pullRequests, compare] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [], pagination: { page: 1, limit: 1, total: 0, totalPages: 0 } })),
    compareUpstream(decodedOwner, decodedName),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="code" pullRequestsCount={pullRequests.pagination?.total ?? pullRequests.data.length} repo={repo} />
      <RepoPageContent>
        <section className="grid gap-3 border-b dark:border-gray-700/50 border-gray-200 p-4">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <h2 className="text-xl font-semibold">Compare with upstream</h2>
              <p className="text-[#59636e]">
                {compare.source ? (
                  <>
                    Original repository:{" "}
                    <Link className="font-semibold text-[#0969da] hover:underline" href={compare.source.url}>
                      {compare.source.owner_handle}/{compare.source.name}
                    </Link>
                  </>
                ) : (
                  "Original repository unavailable."
                )}
              </p>
            </div>
            {compare.behind_by > 0 ? <SyncForkButton name={decodedName} owner={decodedOwner} /> : null}
          </div>
          {compare.status === "unavailable" ? (
            <p className="text-[#59636e]">{compare.message ?? "Upstream comparison is unavailable."}</p>
          ) : (
            <div className="flex flex-wrap items-center gap-3 text-sm text-[#59636e]">
              <span>{compare.ahead_by} commits ahead</span>
              <span>{compare.behind_by} commits behind</span>
              <span className="rounded-full border border-[#d0d7de] px-2 py-0.5">{compare.status.replaceAll("_", " ")}</span>
            </div>
          )}
        </section>
        <div className="grid gap-6 lg:grid-cols-2">
          <CommitList commits={compare.ahead_commits} emptyLabel="No commits ahead of upstream." title="Ahead commits" />
          <CommitList commits={compare.behind_commits} emptyLabel="No upstream commits to sync." title="Behind commits" />
        </div>
        <CodeDiff emptyLabel="No diff to show between this fork and upstream." files={compare.files} />
      </RepoPageContent>
    </div>
  );
}

function CommitList({ commits, emptyLabel, title }: { commits: RepositoryCommit[]; emptyLabel: string; title: string }) {
  return (
    <section className="overflow-hidden rounded-md border border-[#d0d7de] bg-white">
      <header className="border-b border-[#d8dee4] bg-[#f6f8fa] px-4 py-3">
        <h3 className="font-semibold">{title}</h3>
      </header>
      {commits.length === 0 ? (
        <p className="p-4 text-sm text-[#59636e]">{emptyLabel}</p>
      ) : (
        commits.map((commit) => (
          <article className="grid gap-1 border-b border-[#d8dee4] p-4 last:border-b-0" key={commit.sha}>
            <div className="font-semibold">{commit.message}</div>
            <div className="flex flex-wrap items-center gap-3 text-sm text-[#59636e]">
              <span>{commit.author_name}</span>
              <span>{formatDate(commit.created_at)}</span>
              <span className="font-mono text-xs">{commit.sha.slice(0, 12)}</span>
            </div>
          </article>
        ))
      )}
    </section>
  );
}

function formatDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date);
}
