// apps/web/src/app/organizations/[org]/settings/layout.tsx
import Link from "next/link";
import { organizationHref } from "@/lib/routes";

type OrganizationSettingsLayoutProps = {
  children: React.ReactNode;
  params: Promise<{
    org: string;
  }>;
};

export default async function OrganizationSettingsLayout({ children, params }: OrganizationSettingsLayoutProps) {
  const { org } = await params;
  const decodedOrg = decodeURIComponent(org);
  const settingsHref = `${organizationHref(decodedOrg)}/settings`;

  return (
    <div className="grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]">
      <aside className="self-start rounded-md border border-[#d0d7de] bg-white">
        <nav aria-label="Organization settings" className="grid p-2">
          <SettingsLink href={settingsHref} label="General" />
          <SettingsLink href={`${settingsHref}/collaborators`} label="Collaborators" />
          <SettingsLink href={`${settingsHref}/secrets`} label="Secrets and variables" />
        </nav>
      </aside>
      {children}
    </div>
  );
}

function SettingsLink({ href, label }: { href: string; label: string }) {
  return (
    <Link className="rounded-md px-3 py-2 font-semibold text-[#59636e] hover:bg-[#f6f8fa] hover:text-[#1f2328]" href={href}>
      {label}
    </Link>
  );
}

// apps/qwik-web/src/routes/organizations/[org]/settings/layout.tsx
import { Slot, component$ } from "@builder.io/qwik";
import { Link, useLocation } from "@builder.io/qwik-city";

export default component$(() => {
  const location = useLocation();
  const settingsHref = `/organizations/${encodeURIComponent(location.params.org)}/settings`;

  return (
    <div class="settings-layout">
      <aside class="settings-layout__sidebar">
        <nav aria-label="Organization settings" class="settings-layout__nav">
          <SettingsLink href={settingsHref} label="General" />
          <SettingsLink
            href={`${settingsHref}/collaborators`}
            label="Collaborators"
          />
          <SettingsLink
            href={`${settingsHref}/secrets`}
            label="Secrets and variables"
          />
          <SettingsLink href={`${settingsHref}/runners`} label="Runners" />
        </nav>
      </aside>
      <section class="settings-layout__content">
        <Slot />
      </section>
    </div>
  );
});

const SettingsLink = component$(({ href, label }: { href: string; label: string }) => {
  const location = useLocation();

  return (
    <Link
      class={[
        "settings-layout__link",
        location.url.pathname === href ? "settings-layout__link--active" : "",
      ]}
      href={href}
    >
      {label}
    </Link>
  );
});
