// apps/web/src/app/[owner]/[name]/releases/new/page.tsx
import { ReleaseCreatePanel } from "@/components/RepositoryReleasesPanel";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { getRepository, listPullRequests, listReleases, listRepositoryBranches, listRepositoryTags } from "@/lib/api";

type Props = {
  params: Promise<{
    owner: string;
    name: string;
  }>;
};

export default async function NewRepositoryReleasePage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const baseHref = repoHref(decodedOwner, decodedName);
  const [repo, pullRequests, releaseCount, tags, branches] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [] })),
    listReleases(decodedOwner, decodedName, { page: 1, limit: 1, status: "published" }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    listRepositoryTags(decodedOwner, decodedName).catch(() => ({ data: [] })),
    listRepositoryBranches(decodedOwner, decodedName).catch(() => ({ data: [] })),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="releases" pullRequestsCount={pullRequests.data.length} releasesCount={releaseCount.pagination.total} repo={repo} />

      <RepoPageContent>
        <ReleaseCreatePanel baseHref={baseHref} branches={branches.data} name={decodedName} owner={decodedOwner} tags={tags.data} />
      </RepoPageContent>
    </div>
  );
}

// apps/qwik-web/src/routes/[owner]/[name]/releases/new/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { ReleaseCreatePanel } from "~/components/releases/RepositoryReleasesPanel";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import {
  getRepository,
  listPullRequests,
  listReleases,
  listRepositoryBranches,
  listRepositoryTags,
} from "~/lib/api";

export const useNewRepositoryReleasePage = routeLoader$(async ({ params }) => {
  const [repo, pullRequests, releaseCount, tags, branches] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    listReleases(params.owner, params.name, {
      page: 1,
      limit: 1,
      status: "published",
    }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    listRepositoryTags(params.owner, params.name).catch(() => ({ data: [] })),
    listRepositoryBranches(params.owner, params.name).catch(() => ({ data: [] })),
  ]);

  return {
    baseHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}`,
    branches: branches.data,
    name: params.name,
    owner: params.owner,
    pullRequestsCount: pullRequests.pagination.total,
    releasesCount: releaseCount.pagination.total,
    repo,
    tags: tags.data,
  };
});

export default component$(() => {
  const route = useNewRepositoryReleasePage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="releases"
        pullRequestsCount={route.value.pullRequestsCount}
        releasesCount={route.value.releasesCount}
        repo={route.value.repo}
      />
      <RepoPageContent>
        <ReleaseCreatePanel
          baseHref={route.value.baseHref}
          branches={route.value.branches}
          name={route.value.name}
          owner={route.value.owner}
          tags={route.value.tags}
        />
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "New Release · Diggit",
};
