// apps/web/src/app/[owner]/[name]/actions/page.tsx
import Link from "next/link";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { getRepository, listPullRequests } from "@/lib/api";

type Props = {
  params: Promise<{
    owner: string;
    name: string;
  }>;
};

export default async function RepositoryActionsPage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const baseHref = repoHref(decodedOwner, decodedName);
  const [repo, pullRequests] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [], pagination: { page: 1, limit: 1, total: 0, totalPages: 0 } })),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="actions" pullRequestsCount={pullRequests.pagination?.total ?? pullRequests.data.length} repo={repo} />

      <RepoPageContent>
        <section>
          <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3">
            <div>
              <h2 className="text-base font-semibold">Actions</h2>
              <p className="text-sm text-[#59636e]">Manage repository automation and runner capacity.</p>
            </div>
            <Link
              className="inline-flex rounded-md border border-black/15 bg-[#1a7f37] px-3 py-1.5 font-bold text-white hover:bg-[#116329]"
              href={`${baseHref}/settings/runners`}
            >
              Manage runners
            </Link>
          </div>
        </section>
      </RepoPageContent>
    </div>
  );
}

// apps/qwik-web/src/routes/[owner]/[name]/actions/index.tsx
import { component$ } from "@builder.io/qwik";
import { Link, type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";
import {
  RepoHeader,
  RepoPageContent,
} from "~/components/repository/RepoHeader";
import { getRepository, listPullRequests } from "~/lib/api";

export const useRepositoryActionsPage = routeLoader$(async ({ params }) => {
  const [repo, pullRequests] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
  ]);

  return {
    baseHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}`,
    pullRequestsCount: pullRequests.pagination?.total ?? pullRequests.data.length,
    repo,
  };
});

export default component$(() => {
  const route = useRepositoryActionsPage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="actions"
        pullRequestsCount={route.value.pullRequestsCount}
        repo={route.value.repo}
      />

      <RepoPageContent>
        <section class="repository-actions-page">
          <div>
            <h2 class="repository-actions-page__title">Actions</h2>
            <p class="repository-actions-page__description">
              Manage repository automation and runner capacity.
            </p>
          </div>
          <Link
            class="settings-resource-panel__primary-button repository-actions-page__button"
            href={`${route.value.baseHref}/settings/runners`}
          >
            Manage runners
          </Link>
        </section>
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Repository Actions · Diggit",
};
