// apps/web/src/app/organizations/page.tsx
import { OrganizationPanel } from "@/components/OrganizationPanel";

export default function OrganizationsPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">Organizations</p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">Teams</h1>
        <p className="text-[#59636e]">
          Create shared namespaces for repositories, runners, and collaboration.
        </p>
      </section>
      <OrganizationPanel />
    </div>
  );
}

// apps/qwik-web/src/routes/organizations/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { OrganizationPanel } from "~/components/organizations/OrganizationPanel";

export default component$(() => {
  return (
    <div class="organizations-page">
      <section class="organizations-page__hero">
        <p class="organizations-page__eyebrow">Organizations</p>
        <h1 class="organizations-page__title">Teams</h1>
        <p class="organizations-page__description">
          Create shared namespaces for repositories, runners, and collaboration.
        </p>
      </section>
      <OrganizationPanel />
    </div>
  );
});

export const head: DocumentHead = {
  title: "Organizations · Diggit",
  meta: [
    {
      name: "description",
      content:
        "Create and manage shared Diggit organizations for repositories and collaboration.",
    },
  ],
};
