// apps/web/src/app/[owner]/[name]/settings/runners/page.tsx
import { RunnerPanel } from "@/components/RunnerPanel";

type Props = {
  params: Promise<{ owner: string; name: string }>;
};

export default async function RepositoryRunnersPage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);

  return (
    <div className="grid gap-6">
      <section className="grid gap-2">
        <h2 className="text-2xl font-semibold tracking-tight">Repository runners</h2>
        <p className="text-[#59636e]">Manage repository-scope Gitea-compatible runners.</p>
      </section>
      <RunnerPanel
        listPath={`/repos/${encodeURIComponent(decodedOwner)}/${encodeURIComponent(decodedName)}/actions/runners`}
        scopeLabel={`${decodedOwner}/${decodedName}`}
        tokenPath={`/repos/${encodeURIComponent(decodedOwner)}/${encodeURIComponent(decodedName)}/actions/runners/registration-token`}
      />
    </div>
  );
}

// apps/qwik-web/src/routes/[owner]/[name]/settings/runners/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { RunnerPanel } from "~/components/settings/RunnerPanel";

export const useRepositoryRunnersPage = routeLoader$(({ params }) => {
  return {
    encodedName: encodeURIComponent(params.name),
    encodedOwner: encodeURIComponent(params.owner),
    name: params.name,
    owner: params.owner,
  };
});

export default component$(() => {
  const route = useRepositoryRunnersPage();

  return (
    <div class="settings-group-page">
      <section class="settings-group-page__copy">
        <h2 class="settings-group-page__title">Repository runners</h2>
        <p class="settings-group-page__description">
          Manage repository-scope Gitea-compatible runners.
        </p>
      </section>
      <RunnerPanel
        listPath={`/repos/${route.value.encodedOwner}/${route.value.encodedName}/actions/runners`}
        scopeLabel={`${route.value.owner}/${route.value.name}`}
        tokenPath={`/repos/${route.value.encodedOwner}/${route.value.encodedName}/actions/runners/registration-token`}
      />
    </div>
  );
});
