// apps/qwik-web/src/routes/[owner]/[name]/commits/[sha]/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { RepoHeader, RepoPageContent } from "~/components/repository/RepoHeader";
import { CodeDiff } from "~/components/repository/code/CodeDiff";
import { getCommit, getRepository, listPullRequests } from "~/lib/api";

export const useCommitDetailPage = routeLoader$(async ({ params, url }) => {
  const focusPath = url.searchParams.get("path") ?? undefined;
  const [repo, pullRequests, detail] = await Promise.all([
    getRepository(params.owner, params.name),
    listPullRequests(params.owner, params.name, { limit: 1 }).catch(() => ({
      data: [],
      pagination: { page: 1, limit: 1, total: 0, totalPages: 0 },
    })),
    getCommit(params.owner, params.name, params.sha),
  ]);

  return {
    baseHref: `/${encodeURIComponent(params.owner)}/${encodeURIComponent(params.name)}`,
    detail,
    focusPath,
    pullRequestsCount: pullRequests.pagination.total,
    repo,
  };
});

export default component$(() => {
  const route = useCommitDetailPage();

  return (
    <div class="repository-route">
      <RepoHeader
        activeTab="code"
        pullRequestsCount={route.value.pullRequestsCount}
        repo={route.value.repo}
      />
      <RepoPageContent>
        <section class="compare-page__hero">
          <a class="issue-detail-page__back" href={`${route.value.baseHref}/commits`}>
            Back to commits
          </a>
          <h2 class="compare-page__title">{route.value.detail.commit.message}</h2>
          <div class="compare-page__stats">
            <span>{route.value.detail.commit.author_name}</span>
            <span>{formatDate(route.value.detail.commit.created_at)}</span>
            <span class="compare-commits__sha">{route.value.detail.commit.sha}</span>
          </div>
          {route.value.detail.parents.length > 0 ? (
            <p class="issue-detail-page__meta">
              Parent {route.value.detail.parents.map((parent) => parent.slice(0, 12)).join(", ")}
            </p>
          ) : null}
        </section>

        <CodeDiff files={route.value.detail.files} focusPath={route.value.focusPath} />
      </RepoPageContent>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Commit Detail · Diggit",
};

function formatDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : new Intl.DateTimeFormat("en", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(date);
}

// apps/web/src/app/[owner]/[name]/commits/[sha]/page.tsx
import Link from "next/link";
import { CodeDiff } from "@/components/CodeDiff";
import { RepoHeader, RepoPageContent, repoHref } from "@/components/RepoHeader";
import { getCommit, getRepository, listPullRequests } from "@/lib/api";

type Props = {
  params: Promise<{
    owner: string;
    name: string;
    sha: string;
  }>;
  searchParams: Promise<{ path?: string }>;
};

export default async function CommitDetailPage({ params, searchParams }: Props) {
  const { owner, name, sha } = await params;
  const { path } = await searchParams;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const decodedSha = decodeURIComponent(sha);
  const focusPath = path ? decodeURIComponent(path) : undefined;
  const baseHref = repoHref(decodedOwner, decodedName);
  const [repo, pullRequests, detail] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listPullRequests(decodedOwner, decodedName).catch(() => ({ data: [], pagination: { page: 1, limit: 1, total: 0, totalPages: 0 } })),
    getCommit(decodedOwner, decodedName, decodedSha),
  ]);

  return (
    <div className="grid gap-6">
      <RepoHeader activeTab="code" pullRequestsCount={pullRequests.pagination?.total ?? pullRequests.data.length} repo={repo} />
      <RepoPageContent>
        <section className="grid gap-3 rounded-md border border-[#d0d7de] bg-white p-4">
          <Link className="text-sm font-semibold text-[#0969da] hover:underline" href={`${baseHref}/commits`}>
            Back to commits
          </Link>
          <h2 className="text-xl font-semibold">{detail.commit.message}</h2>
          <div className="flex flex-wrap items-center gap-3 text-sm text-[#59636e]">
            <span>{detail.commit.author_name}</span>
            <span>{formatDate(detail.commit.created_at)}</span>
            <span className="font-mono text-xs">{detail.commit.sha}</span>
          </div>
          {detail.parents.length > 0 ? (
            <p className="text-sm text-[#59636e]">Parent {detail.parents.map((parent) => parent.slice(0, 12)).join(", ")}</p>
          ) : null}
        </section>
        <CodeDiff files={detail.files} focusPath={focusPath} />
      </RepoPageContent>
    </div>
  );
}

function formatDate(value: string) {
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date);
}
