// apps/qwik-web/src/routes/[owner]/[name]/settings/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { RepositoryGeneralSettingsForm } from "~/components/settings/RepositoryGeneralSettingsForm";
import { getRepository, listRepositoryBranches } from "~/lib/api";

export const useRepositorySettingsPage = routeLoader$(async ({ params }) => {
  const [repo, branches] = await Promise.all([
    getRepository(params.owner, params.name),
    listRepositoryBranches(params.owner, params.name).catch(() => ({ data: [] })),
  ]);
  const redirectTo =
    repo.owner?.kind === "organization"
      ? `/organizations/${encodeURIComponent(repo.owner_handle)}/repositories`
      : `/${encodeURIComponent(repo.owner_handle)}`;

  return {
    branches: branches.data,
    redirectTo,
    repository: repo,
  };
});

export default component$(() => {
  const route = useRepositorySettingsPage();

  return (
    <RepositoryGeneralSettingsForm
      branches={route.value.branches}
      redirectTo={route.value.redirectTo}
      repository={route.value.repository}
    />
  );
});

// apps/web/src/app/[owner]/[name]/settings/page.tsx
import { RepositoryGeneralSettingsForm } from "@/components/RepositoryGeneralSettingsForm";
import { getRepository, listRepositoryBranches } from "@/lib/api";

type Props = {
  params: Promise<{ owner: string; name: string }>;
};

export default async function RepositorySettingsPage({ params }: Props) {
  const { owner, name } = await params;
  const decodedOwner = decodeURIComponent(owner);
  const decodedName = decodeURIComponent(name);
  const [repo, branches] = await Promise.all([
    getRepository(decodedOwner, decodedName),
    listRepositoryBranches(decodedOwner, decodedName).catch(() => ({ data: [] })),
  ]);
  const redirectTo =
    repo.owner?.kind === "organization"
      ? `/organizations/${encodeURIComponent(repo.owner_handle)}/repositories`
      : `/${encodeURIComponent(repo.owner_handle)}`;

  return <RepositoryGeneralSettingsForm branches={branches.data} redirectTo={redirectTo} repository={repo} />;
}
