// apps/web/src/components/IssueDetailPanel.tsx
"use client";

import { ConversationPanel } from "@/components/ConversationPanel";
import { MarkdownViewer } from "@/components/MarkdownViewer";
import { RepositoryLabelBadges } from "@/components/RepositoryLabelBadges";
import { authHeaders } from "@/lib/auth-session";
import type { ActivityItem, Issue } from "@/lib/api";
import { apiBaseUrl } from "@/lib/runtime-config";
import { useRouter } from "next/navigation";
import { useState } from "react";

const API_URL = apiBaseUrl();

type IssueDetailPanelProps = {
  activity: ActivityItem[];
  baseHref: string;
  issue: Issue;
  name: string;
  owner: string;
};

export function IssueDetailPanel({ activity: initialActivity, baseHref, issue: initialIssue, name, owner }: IssueDetailPanelProps) {
  const router = useRouter();
  const [issue, setIssue] = useState(initialIssue);
  const [message, setMessage] = useState("");
  const commentsUrl = `${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/issues/${issue.number}/comments`;
  const activityUrl = `${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/issues/${issue.number}/activity`;
  const attachmentUploadUrl = `${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/comment-attachments`;

  async function setIssueStatus(nextStatus: "open" | "closed") {
    const response = await fetch(`${API_URL}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/issues/${issue.number}`, {
      method: "PATCH",
      headers: { "content-type": "application/json", ...authHeaders() },
      body: JSON.stringify({ status: nextStatus }),
    });
    if (!response.ok) {
      setMessage(`Failed to update issue: ${response.status}`);
      return;
    }
    setIssue((await response.json()) as Issue);
    setMessage(`Issue ${nextStatus}.`);
    router.refresh();
  }

  return (
    <main className="grid gap-5">
      <a className="text-sm font-semibold text-[#0969da] hover:underline" href={`${baseHref}/issues`}>
        Back to issues
      </a>
      <section className="grid gap-3 rounded-md border border-[#d0d7de] bg-white p-5">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">
              {issue.title} <span className="font-normal text-[#59636e]">#{issue.number}</span>
            </h1>
            <p className="mt-1 text-sm text-[#59636e]">
              Opened by {issue.author_display_name || issue.author_handle} {formatDate(issue.created_at)}
            </p>
          </div>
          <button
            className="rounded-md border border-[#d0d7de] bg-[#f6f8fa] px-3 py-1.5 text-sm font-semibold"
            type="button"
            onClick={() => void setIssueStatus(issue.status === "open" ? "closed" : "open")}
          >
            {issue.status === "open" ? "Close issue" : "Reopen issue"}
          </button>
        </div>
        <RepositoryLabelBadges labels={issue.labels} />
        {issue.body ? <MarkdownViewer content={issue.body} variant="comment" /> : <p className="text-[#59636e]">No description provided.</p>}
      </section>

      {message ? <p className="text-sm text-[#59636e]">{message}</p> : null}

      <ConversationPanel activity={initialActivity} activityUrl={activityUrl} attachmentUploadUrl={attachmentUploadUrl} commentsUrl={commentsUrl} />
    </main>
  );
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value));
}

// apps/qwik-web/src/components/issues/IssueDetailPanel.tsx
import { $, component$, useSignal } from "@builder.io/qwik";

import { ConversationPanel } from "~/components/comments/ConversationPanel";
import { MarkdownViewer } from "~/components/markdown/MarkdownViewer";
import { RepositoryLabelBadges } from "~/components/repository/RepositoryLabelBadges";
import { getAuthToken } from "~/lib/auth-session";
import { publicApiBaseUrl, type ActivityItem, type Issue } from "~/lib/api";

type IssueDetailPanelProps = {
  activity: ActivityItem[];
  baseHref: string;
  issue: Issue;
  name: string;
  owner: string;
};

export const IssueDetailPanel = component$(
  ({ activity, baseHref, issue: initialIssue, name, owner }: IssueDetailPanelProps) => {
    const issue = useSignal(initialIssue);
    const message = useSignal("");
    const commentsUrl = `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/issues/${issue.value.number}/comments`;
    const activityUrl = `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/issues/${issue.value.number}/activity`;
    const attachmentUploadUrl = `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/comment-attachments`;

    const setIssueStatus = $(async (nextStatus: "open" | "closed") => {
      const token = getAuthToken();
      if (!token) {
        message.value = "Sign in to update issues.";
        return;
      }

      const response = await fetch(
        `${publicApiBaseUrl()}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}/issues/${issue.value.number}`,
        {
          method: "PATCH",
          headers: {
            "content-type": "application/json",
            authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({ status: nextStatus }),
        },
      );

      if (!response.ok) {
        message.value = `Failed to update issue: ${response.status}`;
        return;
      }

      issue.value = (await response.json()) as Issue;
      message.value = `Issue ${nextStatus}.`;
    });

    return (
      <main class="issue-detail-page">
        <a class="issue-detail-page__back" href={`${baseHref}/issues`}>
          Back to issues
        </a>

        <section class="issue-detail-page__hero">
          <div class="issue-detail-page__hero-top">
            <div>
              <h1 class="issue-detail-page__title">
                {issue.value.title}{" "}
                <span class="issue-detail-page__number">#{issue.value.number}</span>
              </h1>
              <p class="issue-detail-page__meta">
                Opened by {issue.value.author_display_name || issue.value.author_handle}{" "}
                {formatDate(issue.value.created_at)}
              </p>
            </div>
            <button
              class="issue-detail-page__status-action"
              type="button"
              onClick$={() =>
                setIssueStatus(issue.value.status === "open" ? "closed" : "open")
              }
            >
              {issue.value.status === "open" ? "Close issue" : "Reopen issue"}
            </button>
          </div>

          <RepositoryLabelBadges labels={issue.value.labels} />
          {issue.value.body ? (
            <MarkdownViewer content={issue.value.body} variant="comment" />
          ) : (
            <p class="issue-detail-page__empty-copy">No description provided.</p>
          )}
        </section>

        {message.value ? <p class="issue-detail-page__message">{message.value}</p> : null}

        <ConversationPanel
          activity={activity}
          activityUrl={activityUrl}
          attachmentUploadUrl={attachmentUploadUrl}
          commentsUrl={commentsUrl}
        />
      </main>
    );
  },
);

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(
    new Date(value),
  );
}
