// apps/web/src/app/new/repository/page.tsx
import { CreateRepoForm } from "@/components/RepoActions";

type NewRepositoryPageProps = {
  searchParams: Promise<{
    owner?: string;
  }>;
};

export default async function NewRepositoryPage({ searchParams }: NewRepositoryPageProps) {
  const { owner = "" } = await searchParams;

  return (
    <div className="mx-auto grid max-w-3xl gap-6">
      <section>
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          New project
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">Create a new repository</h1>
        <p className="text-[#59636e]">
          Start a repository under your user namespace or an organization where you have access.
        </p>
      </section>

      <CreateRepoForm initialOwner={owner} />
    </div>
  );
}

// apps/qwik-web/src/routes/new/repository/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import { CreateRepoForm } from "~/components/repositories/CreateRepoForm";

export const useCreateRepositoryPage = routeLoader$(({ url }) => {
  return {
    owner: url.searchParams.get("owner") ?? "",
  };
});

export default component$(() => {
  const data = useCreateRepositoryPage();

  return (
    <div class="new-repository-page">
      <section>
        <p class="new-repository-page__eyebrow">New project</p>
        <h1 class="new-repository-page__title">Create a new repository</h1>
        <p class="new-repository-page__description">
          Start a repository under your user namespace or an organization where
          you have access.
        </p>
      </section>

      <CreateRepoForm initialOwner={data.value.owner} />
    </div>
  );
});

export const head: DocumentHead = {
  title: "New Repository · Diggit",
};
