// apps/qwik-web/src/routes/auth/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { AuthPanel } from "~/components/auth/AuthPanel";

export default component$(() => {
  return (
    <div class="auth-page">
      <section class="auth-page__hero">
        <p class="auth-page__eyebrow">Account</p>
        <h1 class="auth-page__title">Use a local identity for federated Git.</h1>
        <p class="auth-page__description">
          Accounts become ActivityPub actors such as `alice@your-server`, which
          remote servers can display on forks and pull requests.
        </p>
      </section>
      <AuthPanel />
    </div>
  );
});

export const head: DocumentHead = {
  title: "Auth · Diggit",
  meta: [
    {
      name: "description",
      content: "Use a local or federated Diggit identity to sign in.",
    },
  ],
};

// apps/web/src/app/auth/page.tsx
import { AuthPanel } from "@/components/AuthPanel";

export default function AuthPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">Account</p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">Use a local identity for federated Git.</h1>
        <p className="text-[#59636e]">
          Accounts become ActivityPub actors such as `alice@your-server`, which remote servers can
          display on forks and pull requests.
        </p>
      </section>
      <AuthPanel />
    </div>
  );
}
