// apps/qwik-web/src/routes/settings/keys/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { SshKeysPanel } from "~/components/settings/SshKeysPanel";

export default component$(() => {
  return (
    <div class="settings-page">
      <section class="settings-page__hero">
        <p class="settings-page__eyebrow">Account settings</p>
        <h1 class="settings-page__title">SSH keys</h1>
        <p class="settings-page__description">
          Add public keys used for Git SSH access and clone workflows.
        </p>
      </section>
      <SshKeysPanel />
    </div>
  );
});

export const head: DocumentHead = {
  title: "SSH Keys · Diggit",
};

// apps/web/src/app/settings/keys/page.tsx
import { SshKeysPanel } from "@/components/SshKeysPanel";

export default function SshKeysPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          Account settings
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">SSH keys</h1>
        <p className="text-[#59636e]">Add public keys used for Git SSH access and clone workflows.</p>
      </section>
      <SshKeysPanel />
    </div>
  );
}
