// apps/web/src/app/layout.tsx
import type { Metadata } from "next";
import { NavBar } from "@/components/NavBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ThemeScript } from "@/components/ThemeScript";
import "./globals.css";

export const metadata: Metadata = {
  title: "Diggit",
  description: "Federated Git hosting for cross-server forks and pull requests.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className="bg-[#f6f8fa] text-sm leading-6 text-[#1f2328]">
        <ThemeProvider>
          <main className="mx-auto max-w-7xl px-6 pb-12">
            <NavBar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}

// apps/qwik-web/src/routes/layout.tsx
import { Slot, component$ } from "@builder.io/qwik";
import { type DocumentHead } from "@builder.io/qwik-city";
import { NavBar } from "~/components/navigation/NavBar";

export default component$(() => {
  return (
    <main class="app-shell">
      <NavBar />
      <div class="page-shell">
        <Slot />
      </div>
    </main>
  );
});

export const head: DocumentHead = {
  title: "Diggit",
  meta: [
    {
      content: "Federated Git hosting for cross-server forks and pull requests.",
      name: "description",
    },
  ],
};
