// apps/qwik-web/src/routes/settings/oauth/tokens/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { OAuthTokensPanel } from "~/components/settings/OAuthTokensPanel";

export default component$(() => {
  return (
    <div class="settings-page">
      <section class="settings-page__hero">
        <p class="settings-page__eyebrow">Account settings</p>
        <h1 class="settings-page__title">OAuth tokens</h1>
        <p class="settings-page__description">
          Review and revoke tokens issued to OAuth applications.
        </p>
      </section>
      <OAuthTokensPanel />
    </div>
  );
});

export const head: DocumentHead = {
  title: "OAuth Tokens · Diggit",
};

// apps/web/src/app/settings/oauth/tokens/page.tsx
import { OAuthTokensPanel } from "@/components/OAuthTokensPanel";

export default function OAuthTokensPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          Account settings
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">OAuth tokens</h1>
        <p className="text-[#59636e]">Review and revoke tokens issued to OAuth applications.</p>
      </section>
      <OAuthTokensPanel />
    </div>
  );
}
