// apps/web/src/app/new/organization/page.tsx
import { CreateOrganizationForm } from "@/components/OrganizationPanel";

export default function NewOrganizationPage() {
  return (
    <div className="mx-auto grid max-w-3xl gap-6">
      <section>
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          New team namespace
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">Create a new organization</h1>
        <p className="text-[#59636e]">
          Reserve a globally unique owner name for team repositories.
        </p>
      </section>

      <CreateOrganizationForm />
    </div>
  );
}

// apps/qwik-web/src/routes/new/organization/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { CreateOrganizationForm } from "~/components/organizations/OrganizationPanel";

export default component$(() => {
  return (
    <div class="new-organization-page">
      <section>
        <p class="new-organization-page__eyebrow">New team namespace</p>
        <h1 class="new-organization-page__title">Create a new organization</h1>
        <p class="new-organization-page__description">
          Reserve a globally unique owner name for team repositories.
        </p>
      </section>

      <CreateOrganizationForm />
    </div>
  );
});

export const head: DocumentHead = {
  title: "New Organization · Diggit",
  meta: [
    {
      name: "description",
      content: "Create a new shared Diggit organization namespace.",
    },
  ],
};
