// apps/qwik-web/src/routes/organizations/[org]/settings/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { OrganizationGeneralSettingsForm } from "~/components/settings/OrganizationGeneralSettingsForm";
import { getOrganization } from "~/lib/api";

export const useOrganizationSettingsPage = routeLoader$(async ({ params }) => {
  return {
    organization: await getOrganization(params.org),
  };
});

export default component$(() => {
  const route = useOrganizationSettingsPage();

  return <OrganizationGeneralSettingsForm organization={route.value.organization} />;
});

// apps/web/src/app/organizations/[org]/settings/page.tsx
import { OrganizationGeneralSettingsForm } from "@/components/OrganizationGeneralSettingsForm";
import { getOrganization } from "@/lib/api";

type OrganizationSettingsPageProps = {
  params: Promise<{
    org: string;
  }>;
};

export default async function OrganizationSettingsPage({ params }: OrganizationSettingsPageProps) {
  const { org } = await params;
  const organization = await getOrganization(org);

  return <OrganizationGeneralSettingsForm organization={organization} />;
}
