// apps/web/src/app/settings/runners/page.tsx
import { RunnerPanel } from "@/components/RunnerPanel";

export default function UserRunnersPage() {
  return (
    <div className="grid gap-3.5">
      <section className="mb-6">
        <p className="mb-2 inline-flex rounded-full border border-[#d0d7de] bg-[#f6f8fa] px-2.5 py-1 text-[#59636e]">
          Account settings
        </p>
        <h1 className="mb-3 text-4xl font-semibold tracking-tight">User runners</h1>
        <p className="text-[#59636e]">Manage Gitea-compatible runners scoped to your user account.</p>
      </section>
      <RunnerPanel listPath="/user/actions/runners" scopeLabel="User" tokenPath="/user/actions/runners/registration-token" />
    </div>
  );
}

// apps/qwik-web/src/routes/settings/runners/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { RunnerPanel } from "~/components/settings/RunnerPanel";

export default component$(() => {
  return (
    <div class="settings-page">
      <section class="settings-page__hero">
        <p class="settings-page__eyebrow">Account settings</p>
        <h1 class="settings-page__title">User runners</h1>
        <p class="settings-page__description">
          Manage Gitea-compatible runners scoped to your user account.
        </p>
      </section>
      <RunnerPanel
        listPath="/user/actions/runners"
        scopeLabel="User"
        tokenPath="/user/actions/runners/registration-token"
      />
    </div>
  );
});

export const head: DocumentHead = {
  title: "User Runners · Diggit",
};
